#include "crifi_graph_models.h"

//autogenerated by cmake script provides init_graph_modelA_internal
#include "modelA.h"

crifi_graph *init_graph_modelA(){
	crifi_graph *graph = init_graph_modelA_internal(NULL);
	return graph;
}
