#include "crifi_graph_models.h"
#include "crifi_import.h"

//autogenerated by cmake script provides init_graph_modelA_internal
#include "modelA.h"
#include "modelcheckA.h"
#include "modelcheckA.h"
#include "first.h"

crifi_graph *init_graph_modelA(){
	crifi_graph *graph = init_graph_modelA_internal(NULL);
	if (graph != NULL){
		set_model_id_for_import(graph, CRIFI_IMPORT_MODEL_RIFGENERATOR);
	}
	return graph;
}


crifi_graph *init_graph_modelcheckA(){
	crifi_graph *graph = init_graph_modelcheckA_internal(NULL);
	if (graph != NULL){
		set_model_id_for_import(graph, CRIFI_IMPORT_MODEL_RIFGENERATOR);
	}
	return graph;
}

crifi_graph *init_graph_model_first(){
	crifi_graph *graph = init_graph_model_first_internal(NULL);
	if (graph != NULL){
		set_model_id_for_import(graph, CRIFI_IMPORT_MODEL_RIFGENERATOR);
	}
	return graph;
}
