;mydescription

;autogenerated group rules

(defrule rule-gen21183 
(or 	(TripleTemplate
		(subject ?rifrule)
		(predicate <http://www.w3.org/2007/rif#then>)
		(object ?clause))
		(TripleTemplate
		(subject ?rifrule)
		(predicate <http://www.w3.org/2007/rif#formula>)
		(object ?clause))
	)
	(or 	(TripleTemplate
		(subject ?clause)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Frame>))
		(TripleTemplate
		(subject ?clause)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Atom>))
		(TripleTemplate
		(subject ?clause)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#SubClass>))
		(TripleTemplate
		(subject ?clause)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Member>))
	)
		=>
(bind ?clipsaction (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?clause)
		(predicate <http://example.com/as-action>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?clipsaction ))))
	(assert 	(TripleTemplate
		(subject ?clipsaction)
		(predicate <http://example.com/assert-uses-pattern-from>)
		(object ?clause)))

)

(defrule rule-gen21202 
	(TripleTemplate
		(subject ?rifassert)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Assert>))
		(TripleTemplate
		(subject ?rifassert)
		(predicate <http://www.w3.org/2007/rif#target>)
		(object ?clause))
	(or 	(TripleTemplate
		(subject ?clause)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Frame>))
		(TripleTemplate
		(subject ?clause)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Atom>))
		(TripleTemplate
		(subject ?clause)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#SubClass>))
		(TripleTemplate
		(subject ?clause)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Member>))
	)
		=>
(bind ?clipsaction (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?rifassert)
		(predicate <http://example.com/as-action>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?clipsaction ))))
	(assert 	(TripleTemplate
		(subject ?clipsaction)
		(predicate <http://example.com/assert-uses-pattern-from>)
		(object ?clause)))

)

(defrule rule-gen21221 
	(TripleTemplate
		(subject ?rifretract)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Retract>))
		(TripleTemplate
		(subject ?rifretract)
		(predicate <http://www.w3.org/2007/rif#target>)
		(object ?clause))
	(or 	(TripleTemplate
		(subject ?clause)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Frame>))
		(TripleTemplate
		(subject ?clause)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Atom>))
		(TripleTemplate
		(subject ?clause)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#SubClass>))
		(TripleTemplate
		(subject ?clause)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Member>))
	)
		=>
(bind ?clipsaction (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?rifretract)
		(predicate <http://example.com/as-action>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?clipsaction ))))
	(assert 	(TripleTemplate
		(subject ?clipsaction)
		(predicate <http://clips.script/function-name>)
		(object "retract")))
	(assert 	(TripleTemplate
		(subject ?clipsaction)
		(predicate <http://clips.script/function-args>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ))))
	(assert 	(TripleTemplate
		(subject ?clipsaction)
		(predicate <http://example.com/retract-uses-pattern-from>)
		(object ?clause)))

)

(defrule rule-gen21240 
	(TripleTemplate
		(subject ?rifretract)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Retract>))
		(TripleTemplate
		(subject ?rifretract)
		(predicate <http://www.w3.org/2007/rif#target>)
		(object ?rifterm))
		(TripleTemplate
		(subject ?rifterm)
		(predicate <http://example.com/as-expression>)
		(object ?clipsterm))
		=>
(bind ?tmpvar (<http://white.gobo/new-blanknode>))(bind ?tripletemplate (<http://white.gobo/new-blanknode>))(bind ?expandtriples (<http://white.gobo/new-blanknode>))(bind ?triplequery (<http://white.gobo/new-blanknode>))(bind ?findtriples (<http://white.gobo/new-blanknode>))(bind ?clipsretract (<http://white.gobo/new-blanknode>))(bind ?slotsubj (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?rifretract)
		(predicate <http://example.com/as-action>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?clipsretract ))))
	(assert 	(TripleTemplate
		(subject ?clipsretract)
		(predicate <http://clips.script/function-name>)
		(object "retract")))
	(assert 	(TripleTemplate
		(subject ?clipsretract)
		(predicate <http://clips.script/function-args>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?expandtriples ))))
	(assert 	(TripleTemplate
		(subject ?expandtriples)
		(predicate <http://clips.script/function-name>)
		(object "expand%24")))
	(assert 	(TripleTemplate
		(subject ?expandtriples)
		(predicate <http://clips.script/function-args>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?findtriples ))))
	(assert 	(TripleTemplate
		(subject ?findtriples)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://clips.script/FindAllFacts>)))
	(assert 	(TripleTemplate
		(subject ?findtriples)
		(predicate <http://clips.script/fact-set-template>)
		(object ?tripletemplate)))
	(assert 	(TripleTemplate
		(subject ?findtriples)
		(predicate <http://clips.script/query>)
		(object ?triplequery)))
	(assert 	(TripleTemplate
		(subject ?tripletemplate)
		(predicate <http://clips.script/deftemplate-name>)
		(object "TripleTemplate")))
	(assert 	(TripleTemplate
		(subject ?tripletemplate)
		(predicate <http://clips.script/fact-set-member-variable>)
		(object ?tmpvar)))
	(assert 	(TripleTemplate
		(subject ?triplequery)
		(predicate <http://clips.script/function-name>)
		(object "eq")))
	(assert 	(TripleTemplate
		(subject ?triplequery)
		(predicate <http://clips.script/function-args>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?clipsterm ?slotsubj ))))
	(assert 	(TripleTemplate
		(subject ?slotsubj)
		(predicate <http://clips.script/member-variable>)
		(object ?tmpvar)))
	(assert 	(TripleTemplate
		(subject ?slotsubj)
		(predicate <http://clips.script/member-slot-name>)
		(object "subject")))
	(assert 	(TripleTemplate
		(subject ?tmpvar)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://clips.script/Variable>)))

)

(defrule rule-gen21250 
	(TripleTemplate
		(subject ?rifmodify)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Modify>))
		(TripleTemplate
		(subject ?rifmodify)
		(predicate <http://www.w3.org/2007/rif#target>)
		(object ?clause))
		(TripleTemplate
		(subject ?clause)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Frame>))
		(TripleTemplate
		(subject ?clause)
		(predicate <http://www.w3.org/2007/rif#object>)
		(object ?rifobject))
		(TripleTemplate
		(subject ?rifobject)
		(predicate <http://example.com/as-expression>)
		(object ?subjterm))
		=>
(bind ?clipsretractall (<http://white.gobo/new-blanknode>))(bind ?comparepredicate (<http://white.gobo/new-blanknode>))(bind ?comparesubject (<http://white.gobo/new-blanknode>))(bind ?slotsubj (<http://white.gobo/new-blanknode>))(bind ?tmpvar (<http://white.gobo/new-blanknode>))(bind ?comparesubjectandpredicate (<http://white.gobo/new-blanknode>))(bind ?tripletemplate (<http://white.gobo/new-blanknode>))(bind ?clipsassert (<http://white.gobo/new-blanknode>))(bind ?clipsretractvar (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?tmpvar)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://clips.script/Variable>)))
	(assert 	(TripleTemplate
		(subject ?rifmodify)
		(predicate <http://example.com/as-action>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?clipsretractall ?clipsassert ))))
	(assert 	(TripleTemplate
		(subject ?clipsretractall)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://clips.script/DoForAllFacts>)))
	(assert 	(TripleTemplate
		(subject ?clipsretractall)
		(predicate <http://clips.script/fact-set-template>)
		(object ?tripletemplate)))
	(assert 	(TripleTemplate
		(subject ?tripletemplate)
		(predicate <http://clips.script/deftemplate-name>)
		(object "TripleTemplate")))
	(assert 	(TripleTemplate
		(subject ?tripletemplate)
		(predicate <http://clips.script/fact-set-member-variable>)
		(object ?tmpvar)))
	(assert 	(TripleTemplate
		(subject ?clipsretractall)
		(predicate <http://clips.script/query>)
		(object ?comparesubjectandpredicate)))
	(assert 	(TripleTemplate
		(subject ?comparesubjectandpredicate)
		(predicate <http://clips.script/function-name>)
		(object "and")))
	(assert 	(TripleTemplate
		(subject ?comparesubjectandpredicate)
		(predicate <http://clips.script/function-args>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?comparesubject ?comparepredicate ))))
	(assert 	(TripleTemplate
		(subject ?comparesubject)
		(predicate <http://clips.script/function-name>)
		(object "eq")))
	(assert 	(TripleTemplate
		(subject ?comparesubject)
		(predicate <http://clips.script/function-args>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?slotsubj ?subjterm ))))
	(assert 	(TripleTemplate
		(subject ?slotsubj)
		(predicate <http://clips.script/member-variable>)
		(object ?tmpvar)))
	(assert 	(TripleTemplate
		(subject ?slotsubj)
		(predicate <http://clips.script/member-slot-name>)
		(object "subject")))
	(assert 	(TripleTemplate
		(subject ?comparepredicate)
		(predicate <http://clips.script/function-name>)
		(object "or")))
	(assert 	(TripleTemplate
		(subject ?comparepredicate)
		(predicate <http://clips.script/function-args>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ))))
	(assert 	(TripleTemplate
		(subject ?comparepredicate)
		(predicate <http://example.com/compare-slotkeys-varpredicate-rifframe>)
		(object ?clause)))
	(assert 	(TripleTemplate
		(subject ?comparepredicate)
		(predicate <http://example.com/compare-slotkeys-varpredicate-tmpvar>)
		(object ?tmpvar)))
	(assert 	(TripleTemplate
		(subject ?comparepredicate)
		(predicate <http://example.com/add-compare-predicate-from>)
		(object ?clause)))
	(assert 	(TripleTemplate
		(subject ?clipsretractall)
		(predicate <http://clips.script/action>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?clipsretractvar ))))
	(assert 	(TripleTemplate
		(subject ?clipsretractvar)
		(predicate <http://clips.script/function-name>)
		(object "retract")))
	(assert 	(TripleTemplate
		(subject ?clipsretractvar)
		(predicate <http://clips.script/function-args>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?tmpvar ))))
	(assert 	(TripleTemplate
		(subject ?clipsassert)
		(predicate <http://example.com/assert-uses-pattern-from>)
		(object ?clause)))

)

(defrule rule-gen21266 
	(TripleTemplate
		(subject ?comparepredicate)
		(predicate <http://example.com/compare-slotkeys-varpredicate-rifframe>)
		(object ?rifframe))
		(TripleTemplate
		(subject ?comparepredicate)
		(predicate <http://example.com/compare-slotkeys-varpredicate-tmpvar>)
		(object ?tmpvar))
		(TripleTemplate
		(subject ?rifframe)
		(predicate <http://www.w3.org/2007/rif#slots>)
		(object ?slotlist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?slotlist ))
	(test (eq "1^^http://www.w3.org/2001/XMLSchema#integer"(<http://www.w3.org/2007/rif-builtin-function#count> ?slotlist )))
		(TripleTemplate
		(subject ?slot)
		(predicate <http://www.w3.org/2007/rif#slotkey>)
		(object ?slotkey))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?slotlist ?slot ))
		(TripleTemplate
		(subject ?slotkey)
		(predicate <http://example.com/as-expression>)
		(object ?slotkeyterm))
		=>
(bind ?slotpred (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?slotpred)
		(predicate <http://clips.script/member-variable>)
		(object ?tmpvar)))
	(assert 	(TripleTemplate
		(subject ?slotpred)
		(predicate <http://clips.script/member-slot-name>)
		(object "predicate")))
	(do-for-all-facts ((?fct TripleTemplate)) 
		(and 
			(eq ?fct:subject ?comparepredicate)
			(eq ?fct:predicate <http://clips.script/function-name>))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?comparepredicate)
		(predicate <http://clips.script/function-name>)
		(object "eq")))
	(do-for-all-facts ((?fct TripleTemplate)) 
		(and 
			(eq ?fct:subject ?comparepredicate)
			(eq ?fct:predicate <http://clips.script/function-args>))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?comparepredicate)
		(predicate <http://clips.script/function-args>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?slotpred ?slotkeyterm ))))

)

(defrule rule-gen21282 
	(TripleTemplate
		(subject ?clipsassert)
		(predicate <http://example.com/assert-uses-pattern-from>)
		(object ?rifformula))
		(TripleTemplate
		(subject ?rifformula)
		(predicate <http://example.com/as-rhspattern>)
		(object ?rhspattern))
		=>
	(assert 	(TripleTemplate
		(subject ?clipsassert)
		(predicate <http://clips.script/assert>)
		(object ?rhspattern)))

)

(defrule rule-gen21289 
	(TripleTemplate
		(subject ?clipsretract)
		(predicate <http://example.com/retract-uses-pattern-from>)
		(object ?rifformula))
		(TripleTemplate
		(subject ?rifformula)
		(predicate <http://example.com/as-rhspattern>)
		(object ?rhspattern))
		=>
(bind ?clipsassert (<http://white.gobo/new-blanknode>))(do-for-fact ((?trpl TripleTemplate))
		(and (eq ?trpl:subject ?clipsretract) (eq ?trpl:predicate <http://clips.script/function-args>))
		(bind ?retracttargets ?trpl:object))	(do-for-all-facts ((?fct TripleTemplate)) 
		(and 
			(eq ?fct:subject ?clipsretract)
			(eq ?fct:predicate <http://clips.script/function-args>))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?clipsretract)
		(predicate <http://clips.script/function-args>)
		(object (<http://www.w3.org/2007/rif-builtin-function#append> ?retracttargets ?clipsassert ))))
	(assert 	(TripleTemplate
		(subject ?clipsassert)
		(predicate <http://clips.script/assert>)
		(object ?rhspattern)))

)

(defrule rule-gen21296 
	(TripleTemplate
		(subject ?rifatom)
		(predicate <http://www.w3.org/2007/rif#op>)
		(object ?op))
		(TripleTemplate
		(subject ?op)
		(predicate <http://example.com/as-expression>)
		(object ?expressionop))
		=>
(bind ?rhspattern (<http://white.gobo/new-blanknode>))(bind ?slotargs (<http://white.gobo/new-blanknode>))(bind ?slotop (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?rifatom)
		(predicate <http://example.com/as-rhspattern>)
		(object ?rhspattern)))
	(assert 	(TripleTemplate
		(subject ?rhspattern)
		(predicate <http://clips.script/deftemplate-name>)
		(object "Atom")))
	(assert 	(TripleTemplate
		(subject ?rhspattern)
		(predicate <http://clips.script/slot>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?slotop ?slotargs ))))
	(assert 	(TripleTemplate
		(subject ?slotop)
		(predicate <http://clips.script/slot-name>)
		(object "op")))
	(assert 	(TripleTemplate
		(subject ?slotop)
		(predicate <http://clips.script/field>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?expressionop ))))
	(assert 	(TripleTemplate
		(subject ?slotargs)
		(predicate <http://clips.script/slot-name>)
		(object "args")))
	(assert 	(TripleTemplate
		(subject ?slotargs)
		(predicate <http://clips.script/field>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ))))

)

(defrule rule-gen21303 
	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://www.w3.org/2007/rif#object>)
		(object ?object))
		(TripleTemplate
		(subject ?rifnode)
		(predicate <http://www.w3.org/2007/rif#slots>)
		(object ?slotlist))
		(TripleTemplate
		(subject ?slot)
		(predicate <http://www.w3.org/2007/rif#slotkey>)
		(object ?slotkey))
		(TripleTemplate
		(subject ?slot)
		(predicate <http://www.w3.org/2007/rif#slotvalue>)
		(object ?slotvalue))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?slotlist ))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?slotlist ?slot ))
		(TripleTemplate
		(subject ?object)
		(predicate <http://example.com/as-expression>)
		(object ?expressionsubject))
		(TripleTemplate
		(subject ?slotkey)
		(predicate <http://example.com/as-expression>)
		(object ?expressionpredicate))
		(TripleTemplate
		(subject ?slotvalue)
		(predicate <http://example.com/as-expression>)
		(object ?expressionobject))
		=>
(bind ?slotsubject (<http://white.gobo/new-blanknode>))(bind ?slotpredicate (<http://white.gobo/new-blanknode>))(bind ?rhspattern (<http://white.gobo/new-blanknode>))(bind ?slotobject (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/as-rhspattern>)
		(object ?rhspattern)))
	(assert 	(TripleTemplate
		(subject ?rhspattern)
		(predicate <http://clips.script/deftemplate-name>)
		(object "TripleTemplate")))
	(assert 	(TripleTemplate
		(subject ?rhspattern)
		(predicate <http://clips.script/slot>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?slotsubject ?slotpredicate ?slotobject ))))
	(assert 	(TripleTemplate
		(subject ?slotsubject)
		(predicate <http://clips.script/slot-name>)
		(object "subject")))
	(assert 	(TripleTemplate
		(subject ?slotsubject)
		(predicate <http://clips.script/field>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?expressionsubject ))))
	(assert 	(TripleTemplate
		(subject ?slotpredicate)
		(predicate <http://clips.script/slot-name>)
		(object "predicate")))
	(assert 	(TripleTemplate
		(subject ?slotpredicate)
		(predicate <http://clips.script/field>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?expressionpredicate ))))
	(assert 	(TripleTemplate
		(subject ?slotobject)
		(predicate <http://clips.script/slot-name>)
		(object "object")))
	(assert 	(TripleTemplate
		(subject ?slotobject)
		(predicate <http://clips.script/field>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?expressionobject ))))

)
;autogenerated group rules

(defrule rule-gen21325 
	(TripleTemplate
		(subject ?defrule)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://clips.script/Defrule>))
		(TripleTemplate
		(subject ?defrule)
		(predicate <http://clips.script/conditional-element>)
		(object ?conditionallist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?conditionallist ))
		(TripleTemplate
		(subject ?pattern)
		(predicate <http://example.com/binds-variable>)
		(object ?bindsvar))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?conditionallist ?pattern ))
		=>
	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/bound-variable>)
		(object ?bindsvar)))

)

(defrule rule-gen21335 
	(TripleTemplate
		(subject ?templatepattern)
		(predicate <http://clips.script/slot>)
		(object ?slotlist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?slotlist ))
		(TripleTemplate
		(subject ?slot)
		(predicate <http://clips.script/constraint>)
		(object ?var))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?slotlist ?slot ))
		(TripleTemplate
		(subject ?var)
		(predicate <http://clips.script/variable-name>)
		(object ?varname))
		=>
	(assert 	(TripleTemplate
		(subject ?templatepattern)
		(predicate <http://example.com/binds-variable>)
		(object ?var)))

)

(defrule rule-gen21345 
	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/transfer-bound-variables-from>)
		(object ?constraint))
		(TripleTemplate
		(subject ?constraint)
		(predicate <http://example.com/binds-variable>)
		(object ?var))
		=>
	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/bound-variable>)
		(object ?var)))

)

(defrule rule-gen21352 
	(TripleTemplate
		(subject ?rifexternal)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#External>))
		(TripleTemplate
		(subject ?rifexternal)
		(predicate <http://www.w3.org/2007/rif#content>)
		(object ?content))
		(TripleTemplate
		(subject ?content)
		(predicate <http://www.w3.org/2007/rif#op>)
		(object ?rifop))
		(TripleTemplate
		(subject ?rifop)
		(predicate <http://example.com/as-expression>)
		(object ?functionsymbol))
		(TripleTemplate
		(subject ?functionsymbol)
		(predicate <http://clips.script/symbol>)
		(object ?functionname))
		(TripleTemplate
		(subject ?content)
		(predicate <http://www.w3.org/2007/rif#args>)
		(object ?rifarglist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?rifarglist ))
		=>
(bind ?function (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?rifexternal)
		(predicate <http://example.com/as-action>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?function ))))
	(assert 	(TripleTemplate
		(subject ?rifexternal)
		(predicate <http://example.com/as-expression>)
		(object ?function)))
	(assert 	(TripleTemplate
		(subject ?function)
		(predicate <http://clips.script/function-name>)
		(object ?functionname)))
	(assert 	(TripleTemplate
		(subject ?function)
		(predicate <http://clips.script/function-args>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ))))
	(assert 	(TripleTemplate
		(subject ?function)
		(predicate <http://example.com/add-args-from>)
		(object ?rifarglist)))

)

(defrule rule-gen21371 
	(TripleTemplate
		(subject ?function)
		(predicate <http://example.com/add-args-from>)
		(object ?rifarglist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?rifarglist ))
		(TripleTemplate
		(subject ?firstarg)
		(predicate <http://example.com/as-expression>)
		(object ?clipsexpression))
	(test (eq ?firstarg(<http://www.w3.org/2007/rif-builtin-function#get> ?rifarglist "0^^http://www.w3.org/2001/XMLSchema#integer" )))
		=>
(do-for-fact ((?trpl TripleTemplate))
		(and (eq ?trpl:subject ?function) (eq ?trpl:predicate <http://clips.script/function-args>))
		(bind ?functionargs ?trpl:object))	(do-for-all-facts ((?fct TripleTemplate)) 
		(and 
			(eq ?fct:subject ?function)
			(eq ?fct:predicate <http://clips.script/function-args>))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?function)
		(predicate <http://clips.script/function-args>)
		(object (<http://www.w3.org/2007/rif-builtin-function#append> ?functionargs ?clipsexpression ))))
	(do-for-all-facts ((?fct TripleTemplate)) 
		(and 
			(eq ?fct:subject ?function)
			(eq ?fct:predicate <http://example.com/add-args-from>))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?function)
		(predicate <http://example.com/add-args-from>)
		(object (<http://www.w3.org/2007/rif-builtin-function#remove> ?rifarglist "0^^http://www.w3.org/2001/XMLSchema#integer" ))))

)
;autogenerated group rules

(defrule rule-gen21378 (declare (salience -1))
	(TripleTemplate
		(subject ?rifexternal)
		(predicate <http://example.com/add-as-pattern>)
		(object ?defrule))
		(TripleTemplate
		(subject ?rifexternal)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#External>))
		(TripleTemplate
		(subject ?rifexternal)
		(predicate <http://example.com/as-expression>)
		(object ?action))
	(not(exists (and 	(TripleTemplate
		(subject ?action)
		(predicate <http://example.com/needs-variable>)
		(object ?var))
	(not 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/bound-variable>)
		(object ?var)))
	)))
		=>
(do-for-fact ((?trpl TripleTemplate))
		(and (eq ?trpl:subject ?defrule) (eq ?trpl:predicate <http://clips.script/conditional-element>))
		(bind ?oldpatternlist ?trpl:object))(bind ?pattern (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?pattern)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://clips.script/TestCE>)))
	(do-for-all-facts ((?fct TripleTemplate)) 
		(and 
			(eq ?fct:subject ?defrule)
			(eq ?fct:predicate <http://clips.script/conditional-element>))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://clips.script/conditional-element>)
		(object (<http://www.w3.org/2007/rif-builtin-function#append> ?oldpatternlist ?pattern ))))
	(assert 	(TripleTemplate
		(subject ?pattern)
		(predicate <http://clips.script/function-call>)
		(object ?action)))

)

(defrule rule-gen21391 (declare (salience -1))
	(TripleTemplate
		(subject ?rifequal)
		(predicate <http://example.com/add-as-pattern>)
		(object ?defrule))
		(TripleTemplate
		(subject ?rifequal)
		(predicate <http://www.w3.org/2007/rif#left>)
		(object ?left))
		(TripleTemplate
		(subject ?rifequal)
		(predicate <http://www.w3.org/2007/rif#right>)
		(object ?right))
		(TripleTemplate
		(subject ?left)
		(predicate <http://example.com/as-expression>)
		(object ?leftexpr))
		(TripleTemplate
		(subject ?right)
		(predicate <http://example.com/as-expression>)
		(object ?rightexpr))
	(not(exists 	(TripleTemplate
		(subject ?leftexpr)
		(predicate <http://clips.script/variable-name>)
		(object ?varname))))
	(not(exists 	(TripleTemplate
		(subject ?rightexpr)
		(predicate <http://clips.script/variable-name>)
		(object ?varname))))
		=>
(bind ?action (<http://white.gobo/new-blanknode>))(bind ?pattern (<http://white.gobo/new-blanknode>))(do-for-fact ((?trpl TripleTemplate))
		(and (eq ?trpl:subject ?defrule) (eq ?trpl:predicate <http://clips.script/conditional-element>))
		(bind ?oldpatternlist ?trpl:object))	(assert 	(TripleTemplate
		(subject ?pattern)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://clips.script/TestCE>)))
	(do-for-all-facts ((?fct TripleTemplate)) 
		(and 
			(eq ?fct:subject ?defrule)
			(eq ?fct:predicate <http://clips.script/conditional-element>))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://clips.script/conditional-element>)
		(object (<http://www.w3.org/2007/rif-builtin-function#append> ?oldpatternlist ?pattern ))))
	(assert 	(TripleTemplate
		(subject ?pattern)
		(predicate <http://clips.script/function-call>)
		(object ?action)))
	(assert 	(TripleTemplate
		(subject ?action)
		(predicate <http://clips.script/function-name>)
		(object "eq")))
	(assert 	(TripleTemplate
		(subject ?action)
		(predicate <http://clips.script/function-args>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?leftexpr ?rightexpr ))))

)

(defrule rule-gen21413 (declare (salience -1))
	(TripleTemplate
		(subject ?rifframe)
		(predicate <http://example.com/add-as-pattern>)
		(object ?defrule))
		(TripleTemplate
		(subject ?rifframe)
		(predicate <http://www.w3.org/2007/rif#object>)
		(object ?frameobject))
		(TripleTemplate
		(subject ?rifframe)
		(predicate <http://www.w3.org/2007/rif#slots>)
		(object ?slotlist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?slotlist ))
		(TripleTemplate
		(subject ?slot)
		(predicate <http://www.w3.org/2007/rif#slotkey>)
		(object ?slotkey))
		(TripleTemplate
		(subject ?slot)
		(predicate <http://www.w3.org/2007/rif#slotvalue>)
		(object ?slotvalue))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?slotlist ?slot ))
		(TripleTemplate
		(subject ?frameobject)
		(predicate <http://example.com/as-constraint>)
		(object ?constraintsubject))
		(TripleTemplate
		(subject ?slotkey)
		(predicate <http://example.com/as-constraint>)
		(object ?constraintpredicate))
		(TripleTemplate
		(subject ?slotvalue)
		(predicate <http://example.com/as-constraint>)
		(object ?constraintobject))
	(not(exists (and 	(TripleTemplate
		(subject ?constraintsubject)
		(predicate <http://example.com/needs-variable>)
		(object ?x))
	(not 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/bound-variable>)
		(object ?x)))
	)))
	(not(exists (and 	(TripleTemplate
		(subject ?constraintpredicate)
		(predicate <http://example.com/needs-variable>)
		(object ?y))
	(not 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/bound-variable>)
		(object ?y)))
	)))
	(not(exists (and 	(TripleTemplate
		(subject ?constraintobject)
		(predicate <http://example.com/needs-variable>)
		(object ?z))
	(not 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/bound-variable>)
		(object ?z)))
	)))
		=>
(bind ?slotobject (<http://white.gobo/new-blanknode>))(bind ?pattern (<http://white.gobo/new-blanknode>))(bind ?slotsubject (<http://white.gobo/new-blanknode>))(do-for-fact ((?trpl TripleTemplate))
		(and (eq ?trpl:subject ?defrule) (eq ?trpl:predicate <http://clips.script/conditional-element>))
		(bind ?oldpatternlist ?trpl:object))(bind ?slotpredicate (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?pattern)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://clips.script/TemplatePatternCE>)))
	(assert 	(TripleTemplate
		(subject ?pattern)
		(predicate <http://clips.script/deftemplate-name>)
		(object "TripleTemplate")))
	(assert 	(TripleTemplate
		(subject ?pattern)
		(predicate <http://clips.script/slot>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?slotsubject ?slotpredicate ?slotobject ))))
	(assert 	(TripleTemplate
		(subject ?slotsubject)
		(predicate <http://clips.script/slot-name>)
		(object "subject")))
	(assert 	(TripleTemplate
		(subject ?slotsubject)
		(predicate <http://clips.script/constraint>)
		(object ?constraintsubject)))
	(assert 	(TripleTemplate
		(subject ?slotpredicate)
		(predicate <http://clips.script/slot-name>)
		(object "predicate")))
	(assert 	(TripleTemplate
		(subject ?slotpredicate)
		(predicate <http://clips.script/constraint>)
		(object ?constraintpredicate)))
	(assert 	(TripleTemplate
		(subject ?slotobject)
		(predicate <http://clips.script/slot-name>)
		(object "object")))
	(assert 	(TripleTemplate
		(subject ?slotobject)
		(predicate <http://clips.script/constraint>)
		(object ?constraintobject)))
	(do-for-all-facts ((?fct TripleTemplate)) 
		(and 
			(eq ?fct:subject ?defrule)
			(eq ?fct:predicate <http://clips.script/conditional-element>))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://clips.script/conditional-element>)
		(object (<http://www.w3.org/2007/rif-builtin-function#append> ?oldpatternlist ?pattern ))))
	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/transfer-bound-variables-from>)
		(object ?constraintsubject)))
	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/transfer-bound-variables-from>)
		(object ?constraintpredicate)))
	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/transfer-bound-variables-from>)
		(object ?constraintobject)))

)
;autogenerated group rules

(defrule rule-gen21447 (declare (salience 50))
	(TripleTemplate
		(subject ?clipsfunction)
		(predicate <http://clips.script/function-args>)
		(object ?arglist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?arglist ))
		(TripleTemplate
		(subject ?arg)
		(predicate <http://clips.script/variable-name>)
		(object ?varname))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?arglist ?arg ))
		=>
	(assert 	(TripleTemplate
		(subject ?clipsfunction)
		(predicate <http://example.com/needs-variable>)
		(object ?arg)))

)
;autogenerated group rules

(defrule rule-gen21454 (declare (salience 10))
	(TripleTemplate
		(subject ?group)
		(predicate <http://www.w3.org/2007/rif#sentences>)
		(object ?sentences))
	(or 	(TripleTemplate
		(subject ?rule)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Implies>))
		(TripleTemplate
		(subject ?rule)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Forall>))
	)
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?sentences ))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?sentences ?rule ))
		=>
(bind ?actionlist (<http://white.gobo/new-blanknode>))(bind ?defrule (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?rule)
		(predicate <http://example.com/as-defrule>)
		(object ?defrule)))
	(assert 	(TripleTemplate
		(subject ?rule)
		(predicate <http://example.com/add-rule-info>)
		(object ?defrule)))
	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://clips.script/Defrule>)))
	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://clips.script/conditional-element>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ))))

)

(defrule rule-gen21464 (declare (salience 10))
	(TripleTemplate
		(subject ?rifrule)
		(predicate <http://example.com/add-rule-info>)
		(object ?defrule))
		(TripleTemplate
		(subject ?rifrule)
		(predicate <http://www.w3.org/2007/rif#then>)
		(object ?rifaction))
		(TripleTemplate
		(subject ?rifaction)
		(predicate <http://example.com/as-action>)
		(object ?action))
		=>
	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://clips.script/action>)
		(object ?action)))

)

(defrule rule-gen21474 (declare (salience 10))
	(TripleTemplate
		(subject ?rifrule)
		(predicate <http://example.com/add-rule-info>)
		(object ?defrule))
		(TripleTemplate
		(subject ?rifrule)
		(predicate <http://www.w3.org/2007/rif#formula>)
		(object ?rifaction))
		(TripleTemplate
		(subject ?rifaction)
		(predicate <http://example.com/as-action>)
		(object ?action))
		=>
	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://clips.script/action>)
		(object ?action)))

)

(defrule rule-gen21484 (declare (salience 10))
	(TripleTemplate
		(subject ?rifrule)
		(predicate <http://example.com/add-rule-info>)
		(object ?defrule))
		(TripleTemplate
		(subject ?rifrule)
		(predicate <http://www.w3.org/2007/rif#formula>)
		(object ?rifclause))
	(or 	(TripleTemplate
		(subject ?rifclause)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Forall>))
		(TripleTemplate
		(subject ?rifclause)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Implies>))
	)
		=>
	(assert 	(TripleTemplate
		(subject ?rifclause)
		(predicate <http://example.com/add-rule-info>)
		(object ?defrule)))

)

(defrule rule-gen21497 (declare (salience 10))
	(TripleTemplate
		(subject ?rifrule)
		(predicate <http://example.com/add-rule-info>)
		(object ?defrule))
		(TripleTemplate
		(subject ?rifrule)
		(predicate <http://www.w3.org/2007/rif#if>)
		(object ?rifcondition))
		=>
	(assert 	(TripleTemplate
		(subject ?rifcondition)
		(predicate <http://example.com/add-as-pattern>)
		(object ?defrule)))

)

(defrule rule-gen21504 (declare (salience 10))
	(TripleTemplate
		(subject ?rifcondition)
		(predicate <http://example.com/add-as-pattern>)
		(object ?defrule))
		(TripleTemplate
		(subject ?rifcondition)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#And>))
		(TripleTemplate
		(subject ?rifcondition)
		(predicate <http://www.w3.org/2007/rif#formulas>)
		(object ?formulalist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?formulalist ))
	(or 	(TripleTemplate
		(subject ?formula)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#And>))
		(TripleTemplate
		(subject ?formula)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Or>))
		(TripleTemplate
		(subject ?formula)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Exists>))
		(TripleTemplate
		(subject ?formula)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#External>))
		(TripleTemplate
		(subject ?formula)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#INeg>))
		(TripleTemplate
		(subject ?formula)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Frame>))
		(TripleTemplate
		(subject ?formula)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Atom>))
		(TripleTemplate
		(subject ?formula)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#SubClass>))
		(TripleTemplate
		(subject ?formula)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Equal>))
	)
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?formulalist ?formula ))
		=>
	(assert 	(TripleTemplate
		(subject ?formula)
		(predicate <http://example.com/add-as-pattern>)
		(object ?defrule)))

)

(defrule rule-gen21541 (declare (salience 10))
	(TripleTemplate
		(subject ?rifrule)
		(predicate <http://example.com/add-rule-info>)
		(object ?defrule))
		(TripleTemplate
		(subject ?rifrule)
		(predicate <http://www.w3.org/2007/rif#then>)
		(object ?rifclause))
		(TripleTemplate
		(subject ?rifclause)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Implies>))
		=>
	(assert 	(TripleTemplate
		(subject ?rifclause)
		(predicate <http://example.com/add-rule-info>)
		(object ?defrule)))

)
;autogenerated group rules

(defrule rule-gen21551 
	(TripleTemplate
		(subject ?directive)
		(predicate <http://www.w3.org/2007/rif#location>)
		(object ?location))
		(TripleTemplate
		(subject ?directive)
		(predicate <http://www.w3.org/2007/rif#profile>)
		(object ?profile))
		=>
(<http://white.gobo/import> ?location ?profile )
)

(defrule rule-gen21558 
	(TripleTemplate
		(subject ?directive)
		(predicate <http://www.w3.org/2007/rif#location>)
		(object ?location))
	(not(exists 	(TripleTemplate
		(subject ?directive)
		(predicate <http://www.w3.org/2007/rif#profile>)
		(object ?profile))))
		=>
	(assert 	(TripleTemplate
		(subject ?directive)
		(predicate <http://www.w3.org/2007/rif#profile>)
		(object <http://www.w3.org/ns/entailment/RIF>)))

)
;autogenerated group rules

(defrule rule-gen21565 
	(TripleTemplate
		(subject ?frame)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Frame>))
		=>
	(assert 	(Member
		(instance ?frame)
		(class <http://example.com/construct-as-conditional>)))
	(assert 	(TripleTemplate
		(subject ?frame)
		(predicate <http://example.com/in-as-conditional>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ))))

)

(defrule rule-gen21569 
	(TripleTemplate
		(subject ?rifineg)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#INeg>))
		(TripleTemplate
		(subject ?rifineg)
		(predicate <http://www.w3.org/2007/rif#formula>)
		(object ?formula))
		(TripleTemplate
		(subject ?formula)
		(predicate <http://example.com/as-conditional>)
		(object ?clipsconditional))
		=>
(bind ?notCE (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?rifineg)
		(predicate <http://example.com/as-conditional>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?notCE ))))
	(assert 	(TripleTemplate
		(subject ?notCE)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://clips.script/NotCE>)))
	(assert 	(TripleTemplate
		(subject ?notCE)
		(predicate <http://clips.script/conditional-element>)
		(object ?clipsconditional)))

)

(defrule rule-gen21579 
	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://www.w3.org/2007/rif#slots>)
		(object ?slotlist))
		(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/in-as-conditional>)
		(object ?existingconditionals))
	(not(exists (and 	(TripleTemplate
		(subject ?slot)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Slot>))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?slotlist ?slot ))
	(not 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/used-slot-for-conditional>)
		(object ?slot)))
	)))
		=>
	(assert 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/as-conditional>)
		(object ?existingconditionals)))

)

(defrule rule-gen21589 
	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Frame>))
		(TripleTemplate
		(subject ?rifnode)
		(predicate <http://www.w3.org/2007/rif#object>)
		(object ?object))
		(TripleTemplate
		(subject ?object)
		(predicate <http://example.com/as-constraint>)
		(object ?constraintsubject))
		(TripleTemplate
		(subject ?rifnode)
		(predicate <http://www.w3.org/2007/rif#slots>)
		(object ?slotlist))
		(TripleTemplate
		(subject ?slot)
		(predicate <http://www.w3.org/2007/rif#slotkey>)
		(object ?slotkey))
		(TripleTemplate
		(subject ?slotkey)
		(predicate <http://example.com/as-constraint>)
		(object ?constraintpredicate))
		(TripleTemplate
		(subject ?slot)
		(predicate <http://www.w3.org/2007/rif#slotvalue>)
		(object ?slotvalue))
		(TripleTemplate
		(subject ?slotvalue)
		(predicate <http://example.com/as-constraint>)
		(object ?constraintobject))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?slotlist ))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?slotlist ?slot ))
		(TripleTemplate
		(subject ?constraintsubject)
		(predicate <http://example.com/as-constraint-needs-additional-conditionals>)
		(object ?additionalconditionalssubject))
		(TripleTemplate
		(subject ?constraintpredicate)
		(predicate <http://example.com/as-constraint-needs-additional-conditionals>)
		(object ?additionalconditionalspredicate))
		(TripleTemplate
		(subject ?constraintobject)
		(predicate <http://example.com/as-constraint-needs-additional-conditionals>)
		(object ?additionalconditionalsobject))
		(Member
		(instance ?rifnode)
		(class <http://example.com/construct-as-conditional>))
	(not 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/used-slot-for-conditional>)
		(object ?slot)))
		=>
(bind ?clipsconditionalelement (<http://white.gobo/new-blanknode>))(bind ?slotsubject (<http://white.gobo/new-blanknode>))(do-for-fact ((?trpl TripleTemplate))
		(and (eq ?trpl:subject ?rifnode) (eq ?trpl:predicate <http://example.com/in-as-conditional>))
		(bind ?existingconditionals ?trpl:object))(bind ?slotobject (<http://white.gobo/new-blanknode>))(bind ?slotpredicate (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/used-slot-for-conditional>)
		(object ?slot)))
	(do-for-all-facts ((?fct TripleTemplate)) 
		(and 
			(eq ?fct:subject ?rifnode)
			(eq ?fct:predicate <http://example.com/in-as-conditional>))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/in-as-conditional>)
		(object (<http://www.w3.org/2007/rif-builtin-function#concatenate> ?existingconditionals ?additionalconditionalssubject ?additionalconditionalspredicate ?additionalconditionalsobject (<http://www.w3.org/2007/rif-builtin-function#make-list> ?clipsconditionalelement ) ))))
	(assert 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/binds-variables>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list>))))
	(assert 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/unbound-variables>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list>))))
	(assert 	(TripleTemplate
		(subject ?clipsconditionalelement)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://clips.script/TemplatePatternCE>)))
	(assert 	(TripleTemplate
		(subject ?clipsconditionalelement)
		(predicate <http://clips.script/deftemplate-name>)
		(object "TripleTemplate")))
	(assert 	(TripleTemplate
		(subject ?clipsconditionalelement)
		(predicate <http://clips.script/slot>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ?slotsubject ?slotpredicate ?slotobject ))))
	(assert 	(TripleTemplate
		(subject ?slotsubject)
		(predicate <http://clips.script/slot-name>)
		(object "subject")))
	(assert 	(TripleTemplate
		(subject ?slotsubject)
		(predicate <http://clips.script/constraint>)
		(object ?constraintsubject)))
	(assert 	(TripleTemplate
		(subject ?slotpredicate)
		(predicate <http://clips.script/slot-name>)
		(object "predicate")))
	(assert 	(TripleTemplate
		(subject ?slotpredicate)
		(predicate <http://clips.script/constraint>)
		(object ?constraintpredicate)))
	(assert 	(TripleTemplate
		(subject ?slotobject)
		(predicate <http://clips.script/slot-name>)
		(object "object")))
	(assert 	(TripleTemplate
		(subject ?slotobject)
		(predicate <http://clips.script/constraint>)
		(object ?constraintobject)))

)
;autogenerated group rules

(defrule rule-gen21625 
	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://www.w3.org/2007/rif#actions>)
		(object ?actionlist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?actionlist ))
		=>
	(assert 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/in-transform-do>)
		(object ?actionlist)))
	(assert 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/out-transform-do>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ))))

)

(defrule rule-gen21629 
	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/in-transform-do>)
		(object ?in))
	(test (eq "0^^http://www.w3.org/2001/XMLSchema#integer"(<http://www.w3.org/2007/rif-builtin-function#count> ?in )))
		(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/out-transform-do>)
		(object ?out))
		=>
	(assert 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/as-action>)
		(object ?out)))
	(do-for-all-facts ((?fct TripleTemplate)) (and (eq ?fct:subject ?rifnode) (and (eq ?fct:predicate <http://example.com/in-transform-do>)(eq ?fct:object ?in)))
		(retract ?fct))	(do-for-all-facts ((?fct TripleTemplate)) (and (eq ?fct:subject ?rifnode) (and (eq ?fct:predicate <http://example.com/out-transform-do>)(eq ?fct:object ?out)))
		(retract ?fct))
)

(defrule rule-gen21636 
	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/in-transform-do>)
		(object ?in))
		(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/out-transform-do>)
		(object ?out))
		(TripleTemplate
		(subject ?firstaction)
		(predicate <http://example.com/as-action>)
		(object ?nextactions))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#numeric-not-equal> "0^^http://www.w3.org/2001/XMLSchema#integer" (<http://www.w3.org/2007/rif-builtin-function#count> ?in ) ))
	(test (eq ?firstaction(<http://www.w3.org/2007/rif-builtin-function#get> ?in "0^^http://www.w3.org/2001/XMLSchema#integer" )))
		=>
	(do-for-all-facts ((?fct TripleTemplate)) 
		(and 
			(eq ?fct:subject ?rifnode)
			(eq ?fct:predicate <http://example.com/in-transform-do>))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/in-transform-do>)
		(object (<http://www.w3.org/2007/rif-builtin-function#remove> ?in "0^^http://www.w3.org/2001/XMLSchema#integer" ))))
	(do-for-all-facts ((?fct TripleTemplate)) 
		(and 
			(eq ?fct:subject ?rifnode)
			(eq ?fct:predicate <http://example.com/out-transform-do>))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/out-transform-do>)
		(object (<http://www.w3.org/2007/rif-builtin-function#concatenate> ?out ?nextactions ))))

)
;autogenerated group rules

(defrule rule-gen21646 
	(TripleTemplate
		(subject ?group)
		(predicate <http://www.w3.org/2007/rif#sentences>)
		(object ?sentences))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?sentences ))
	(exists (and (or 	(TripleTemplate
		(subject ?factable)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Frame>))
		(TripleTemplate
		(subject ?factable)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Member>))
		(TripleTemplate
		(subject ?factable)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Atom>))
	)
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?sentences ?factable ))
	))
		=>
(bind ?deffacts (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?group)
		(predicate <http://example.com/combine-deffacts-in>)
		(object ?deffacts)))
	(assert 	(TripleTemplate
		(subject ?deffacts)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://clips.script/Deffacts>)))
	(assert 	(TripleTemplate
		(subject ?deffacts)
		(predicate <http://clips.script/rhs-pattern>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ))))

)

(defrule rule-gen21659 
	(TripleTemplate
		(subject ?group)
		(predicate <http://www.w3.org/2007/rif#sentences>)
		(object ?sentences))
		(TripleTemplate
		(subject ?group)
		(predicate <http://example.com/combine-deffacts-in>)
		(object ?deffacts))
	(or 	(TripleTemplate
		(subject ?factable)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Frame>))
		(TripleTemplate
		(subject ?factable)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Member>))
		(TripleTemplate
		(subject ?factable)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Atom>))
	)
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?sentences ))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?sentences ?factable ))
		(TripleTemplate
		(subject ?factable)
		(predicate <http://example.com/as-rhspattern>)
		(object ?newrhspattern))
		=>
(do-for-fact ((?trpl TripleTemplate))
		(and (eq ?trpl:subject ?deffacts) (eq ?trpl:predicate <http://clips.script/rhs-pattern>))
		(bind ?rhspatternlist ?trpl:object))	(do-for-all-facts ((?fct TripleTemplate)) 
		(and 
			(eq ?fct:subject ?deffacts)
			(eq ?fct:predicate <http://clips.script/rhs-pattern>))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?deffacts)
		(predicate <http://clips.script/rhs-pattern>)
		(object (<http://www.w3.org/2007/rif-builtin-function#append> ?rhspatternlist ?newrhspattern ))))

)
;autogenerated group rules
;autogenerated group rules

(defrule rule-gen21678 (declare (salience 20))
	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/uses-patterns-as-conditional>)
		(object ?rifrule))
		(TripleTemplate
		(subject ?rifrule)
		(predicate <http://www.w3.org/2007/rif#pattern>)
		(object ?pattern))
		(TripleTemplate
		(subject ?pattern)
		(predicate <http://example.com/as-conditional>)
		(object ?patternconditions))
		(TripleTemplate
		(subject ?pattern)
		(predicate <http://example.com/unbound-variables>)
		(object ?neededboundvars))
		(TripleTemplate
		(subject ?pattern)
		(predicate <http://example.com/binds-variables>)
		(object ?newsuppliedboundvars))
		(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/bound-variables>)
		(object ?suppliedboundvars))
	(test (eq (<http://www.w3.org/2007/rif-builtin-function#make-list>)(<http://www.w3.org/2007/rif-builtin-function#except> ?neededboundvars ?suppliedboundvars )))
	(not 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/added-pattern>)
		(object ?pattern)))
		=>
(do-for-fact ((?trpl TripleTemplate))
		(and (eq ?trpl:subject ?defrule) (eq ?trpl:predicate <http://example.com/out-as-conditional>))
		(bind ?currentconditions ?trpl:object))	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/implemented-pattern>)
		(object ?pattern)))
	(do-for-all-facts ((?fct TripleTemplate)) 
		(and 
			(eq ?fct:subject ?defrule)
			(eq ?fct:predicate <http://example.com/out-as-conditional>))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/out-as-conditional>)
		(object (<http://www.w3.org/2007/rif-builtin-function#concatenate> ?currentconditions ?patternconditions ))))
	(do-for-all-facts ((?fct TripleTemplate)) 
		(and 
			(eq ?fct:subject ?defrule)
			(eq ?fct:predicate <http://example.com/bound-variables>))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/bound-variables>)
		(object (<http://www.w3.org/2007/rif-builtin-function#union> ?suppliedboundvars ?suppliedboundvars ))))
	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/added-pattern>)
		(object ?pattern)))

)
;autogenerated group rules

(defrule rule-gen21697 (declare (salience 3))
	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/uses-patterns-as-conditional>)
		(object ?rifrule))
	(not(exists (and 	(TripleTemplate
		(subject ?rifrule)
		(predicate <http://www.w3.org/2007/rif#pattern>)
		(object ?pattern))
	(not 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/added-pattern>)
		(object ?pattern)))
	)))
		(TripleTemplate
		(subject ?defrule)
		(predicate <http://example.com/out-as-conditional>)
		(object ?conditional))
		=>
	(assert 	(TripleTemplate
		(subject ?defrule)
		(predicate <http://clips.script/conditional-element>)
		(object ?conditional)))

)
;autogenerated group rules
;autogenerated group rules

(defrule rule-gen21707 
	(TripleTemplate
		(subject ?factvar)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://clips.script/Variable>))
		(Atom
		(op <http://example.com/currentfactindex>)
		(args ?factindex ))
	(not(exists 	(TripleTemplate
		(subject ?factvar)
		(predicate <http://clips.script/variable-name>)
		(object ?factname))))
		=>
	(do-for-all-facts ((?fct Atom)) (and (eq ?fct:op <http://example.com/currentfactindex>) (eq ?fct:args (eq ?fct:args (create$  ?factindex))))
		(retract ?fct))	(assert 	(Atom
		(op <http://example.com/currentfactindex>)
		(args (<http://www.w3.org/2007/rif-builtin-function#numeric-add> ?factindex "1^^http://www.w3.org/2001/XMLSchema#integer" ) )))
	(assert 	(TripleTemplate
		(subject ?factvar)
		(predicate <http://clips.script/variable-name>)
		(object (<http://www.w3.org/2007/rif-builtin-function#concat> "fct" ?factindex ))))

)
(deffacts rule-gen21716
		(Atom
		(op <http://example.com/currentfactindex>)
		(args "1^^http://www.w3.org/2001/XMLSchema#integer" )))

;autogenerated group rules

(defrule rule-gen21717 
(or 	(TripleTemplate
		(subject ?parent)
		(predicate <http://www.w3.org/2007/rif#formula>)
		(object ?child))
		(TripleTemplate
		(subject ?parent)
		(predicate <http://www.w3.org/2007/rif#object>)
		(object ?child))
		(TripleTemplate
		(subject ?parent)
		(predicate <http://www.w3.org/2007/rif#if>)
		(object ?child))
		(TripleTemplate
		(subject ?parent)
		(predicate <http://www.w3.org/2007/rif#then>)
		(object ?child))
		(TripleTemplate
		(subject ?parent)
		(predicate <http://www.w3.org/2007/rif#target>)
		(object ?child))
		(TripleTemplate
		(subject ?parent)
		(predicate <http://www.w3.org/2007/rif#content>)
		(object ?child))
		(TripleTemplate
		(subject ?parent)
		(predicate <http://www.w3.org/2007/rif#op>)
		(object ?child))
		(TripleTemplate
		(subject ?parent)
		(predicate <http://www.w3.org/2007/rif#payload>)
		(object ?child))
		(TripleTemplate
		(subject ?parent)
		(predicate <http://www.w3.org/2007/rif#pattern>)
		(object ?child))
	)
		=>
	(assert 	(TripleTemplate
		(subject ?parent)
		(predicate <http://example.com/inherits-data>)
		(object ?child)))

)

(defrule rule-gen21745 
	(TripleTemplate
		(subject ?parent)
		(predicate <http://www.w3.org/2007/rif#slots>)
		(object ?slotlist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?slotlist ))
		(TripleTemplate
		(subject ?slot)
		(predicate <http://www.w3.org/2007/rif#slotkey>)
		(object ?childkey))
		(TripleTemplate
		(subject ?slot)
		(predicate <http://www.w3.org/2007/rif#slotvalue>)
		(object ?childvalue))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?slotlist ?slot ))
		=>
	(assert 	(TripleTemplate
		(subject ?parent)
		(predicate <http://example.com/inherits-data>)
		(object ?childkey)))
	(assert 	(TripleTemplate
		(subject ?parent)
		(predicate <http://example.com/inherits-data>)
		(object ?childvalue)))

)

(defrule rule-gen21755 
(or 	(TripleTemplate
		(subject ?parent)
		(predicate <http://www.w3.org/2007/rif#sentences>)
		(object ?childlist))
		(TripleTemplate
		(subject ?parent)
		(predicate <http://www.w3.org/2007/rif#formulas>)
		(object ?childlist))
		(TripleTemplate
		(subject ?parent)
		(predicate <http://www.w3.org/2007/rif#actions>)
		(object ?childlist))
		(TripleTemplate
		(subject ?parent)
		(predicate <http://www.w3.org/2007/rif#args>)
		(object ?childlist))
	)
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?childlist ))
	(or 	(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Group>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Forall>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Frame>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Atom>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Assert>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Retract>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Do>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Modify>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Subclass>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Equal>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Member>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Var>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Const>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#And>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Or>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Not>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Exists>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#External>))
		(TripleTemplate
		(subject ?child)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Execute>))
	)
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?childlist ?child ))
		=>
	(assert 	(TripleTemplate
		(subject ?parent)
		(predicate <http://example.com/inherits-data>)
		(object ?child)))

)

(defrule rule-gen21825 
	(TripleTemplate
		(subject ?rifdo)
		(predicate <http://www.w3.org/2007/rif#actionVar>)
		(object ?actionvar))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?actionvar ))
		(TripleTemplate
		(subject ?rifvar)
		(predicate <http://www.w3.org/2007/rif#varname>)
		(object ?varname))
		(TripleTemplate
		(subject ?rifframe)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Frame>))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?actionvar ?rifvar ))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?actionvar ?rifframe ))
		=>
	(assert 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/inherits-data>)
		(object ?rifframe)))
	(assert 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/inherits-data>)
		(object ?rifdo)))

)

(defrule rule-gen21835 
	(TripleTemplate
		(subject ?parent)
		(predicate <http://example.com/inherits-data>)
		(object ?child))
		(TripleTemplate
		(subject ?child)
		(predicate <http://example.com/inherits-data>)
		(object ?grandchild))
		=>
	(assert 	(TripleTemplate
		(subject ?parent)
		(predicate <http://example.com/inherits-data>)
		(object ?grandchild)))

)
;autogenerated group rules

(defrule rule-gen21842 
	(TripleTemplate
		(subject ?rifdo)
		(predicate <http://www.w3.org/2007/rif#actionVar>)
		(object ?actionvar))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?actionvar ))
		(TripleTemplate
		(subject ?rifvar)
		(predicate <http://www.w3.org/2007/rif#varname>)
		(object ?varname))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?actionvar ?rifvar ))
		=>
(bind ?clipsnode (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/as-constraint>)
		(object ?clipsnode)))
	(assert 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/as-expression>)
		(object ?clipsnode)))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://clips.script/variable-name>)
		(object ?varname)))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://example.com/as-constraint-needs-additional-conditionals>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ))))
	(assert 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/inherits-data>)
		(object ?rifdo)))

)

(defrule rule-gen21849 
	(TripleTemplate
		(subject ?rifforall)
		(predicate <http://www.w3.org/2007/rif#vars>)
		(object ?varlist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?varlist ))
		(TripleTemplate
		(subject ?rifvar)
		(predicate <http://www.w3.org/2007/rif#varname>)
		(object ?varname))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?varlist ?rifvar ))
		=>
	(assert 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/inherits-data>)
		(object ?rifforall)))

)

(defrule rule-gen21856 
	(TripleTemplate
		(subject ?rifforall)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Forall>))
		(TripleTemplate
		(subject ?rifforall)
		(predicate <http://www.w3.org/2007/rif#vars>)
		(object ?varlist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?varlist ))
		(TripleTemplate
		(subject ?rifvar)
		(predicate <http://www.w3.org/2007/rif#varname>)
		(object ?varname))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?varlist ?rifvar ))
		=>
(bind ?clipsnode (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/as-constraint>)
		(object ?clipsnode)))
	(assert 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/as-expression>)
		(object ?clipsnode)))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://clips.script/variable-name>)
		(object ?varname)))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://example.com/as-constraint-needs-additional-conditionals>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ))))

)

(defrule rule-gen21866 
	(TripleTemplate
		(subject ?rifexists)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Exists>))
		(TripleTemplate
		(subject ?rifexists)
		(predicate <http://www.w3.org/2007/rif#vars>)
		(object ?varlist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?varlist ))
		(TripleTemplate
		(subject ?rifvar)
		(predicate <http://www.w3.org/2007/rif#varname>)
		(object ?varname))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?varlist ?rifvar ))
	(not(exists 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/as-expression>)
		(object ?expr))))
		(TripleTemplate
		(subject ?rifvarchild)
		(predicate <http://www.w3.org/2007/rif#varname>)
		(object ?varname))
		(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/inherits-data>)
		(object ?rifvarchild))
		(TripleTemplate
		(subject ?rifframe)
		(predicate <http://www.w3.org/2007/rif#object>)
		(object ?rifvarchild))
		(TripleTemplate
		(subject ?rifframe)
		(predicate <http://example.com/as-expression>)
		(object ?factvar))
		=>
(bind ?clipsnode (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/as-constraint>)
		(object ?clipsnode)))
	(assert 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/as-expression>)
		(object ?clipsnode)))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://clips.script/member-variable>)
		(object ?factvar)))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://clips.script/member-slot-name>)
		(object "subject")))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://example.com/as-constraint-needs-additional-conditionals>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ))))

)

(defrule rule-gen21891 
	(TripleTemplate
		(subject ?rifexists)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Exists>))
		(TripleTemplate
		(subject ?rifexists)
		(predicate <http://www.w3.org/2007/rif#vars>)
		(object ?varlist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?varlist ))
		(TripleTemplate
		(subject ?rifvar)
		(predicate <http://www.w3.org/2007/rif#varname>)
		(object ?varname))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?varlist ?rifvar ))
	(not(exists 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/as-expression>)
		(object ?expr))))
		(TripleTemplate
		(subject ?rifvarchild)
		(predicate <http://www.w3.org/2007/rif#varname>)
		(object ?varname))
		(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/inherits-data>)
		(object ?rifvarchild))
		(TripleTemplate
		(subject ?rifframe)
		(predicate <http://www.w3.org/2007/rif#slots>)
		(object ?slotlist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?slotlist ))
		(TripleTemplate
		(subject ?rifslot)
		(predicate <http://www.w3.org/2007/rif#slotkey>)
		(object ?rifvarchild))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?slotlist ?rifslot ))
		(TripleTemplate
		(subject ?rifframe)
		(predicate <http://example.com/as-expression>)
		(object ?factvar))
		=>
(bind ?clipsnode (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/as-constraint>)
		(object ?clipsnode)))
	(assert 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/as-expression>)
		(object ?clipsnode)))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://clips.script/member-variable>)
		(object ?factvar)))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://clips.script/member-slot-name>)
		(object "predicate")))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://example.com/as-constraint-needs-additional-conditionals>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ))))

)

(defrule rule-gen21919 
	(TripleTemplate
		(subject ?rifexists)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2007/rif#Exists>))
		(TripleTemplate
		(subject ?rifexists)
		(predicate <http://www.w3.org/2007/rif#vars>)
		(object ?varlist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?varlist ))
		(TripleTemplate
		(subject ?rifvar)
		(predicate <http://www.w3.org/2007/rif#varname>)
		(object ?varname))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?varlist ?rifvar ))
	(not(exists 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/as-expression>)
		(object ?expr))))
		(TripleTemplate
		(subject ?rifvarchild)
		(predicate <http://www.w3.org/2007/rif#varname>)
		(object ?varname))
		(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/inherits-data>)
		(object ?rifvarchild))
		(TripleTemplate
		(subject ?rifframe)
		(predicate <http://www.w3.org/2007/rif#slots>)
		(object ?slotlist))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?slotlist ))
		(TripleTemplate
		(subject ?rifslot)
		(predicate <http://www.w3.org/2007/rif#slotvalue>)
		(object ?rifvarchild))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#list-contains> ?slotlist ?rifslot ))
		(TripleTemplate
		(subject ?rifframe)
		(predicate <http://example.com/as-expression>)
		(object ?factvar))
		=>
(bind ?clipsnode (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/as-constraint>)
		(object ?clipsnode)))
	(assert 	(TripleTemplate
		(subject ?rifvar)
		(predicate <http://example.com/as-expression>)
		(object ?clipsnode)))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://clips.script/member-variable>)
		(object ?factvar)))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://clips.script/member-slot-name>)
		(object "object")))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://example.com/as-constraint-needs-additional-conditionals>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ))))

)

(defrule rule-gen21947 
	(TripleTemplate
		(subject ?varparent)
		(predicate <http://example.com/inherits-data>)
		(object ?varchild))
		(TripleTemplate
		(subject ?varparent)
		(predicate <http://www.w3.org/2007/rif#varname>)
		(object ?varname))
		(TripleTemplate
		(subject ?varchild)
		(predicate <http://www.w3.org/2007/rif#varname>)
		(object ?varname))
		(TripleTemplate
		(subject ?varparent)
		(predicate <http://example.com/as-expression>)
		(object ?clipsvar))
		=>
	(assert 	(TripleTemplate
		(subject ?varchild)
		(predicate <http://example.com/as-expression>)
		(object ?clipsvar)))
	(assert 	(TripleTemplate
		(subject ?varchild)
		(predicate <http://example.com/as-constraint>)
		(object ?clipsvar)))

)
;autogenerated group rules

(defrule rule-gen21960 
	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://www.w3.org/2007/rif#value>)
		(object ?value))
		=>
(bind ?clipsnode (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/as-constraint>)
		(object ?clipsnode)))
	(assert 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/as-expression>)
		(object ?clipsnode)))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://clips.script/string>)
		(object (<http://white.gobo/literal-to-clipsconstant> ?value ))))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://example.com/as-constraint-needs-additional-conditionals>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ))))

)

(defrule rule-gen21964 
	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://www.w3.org/2007/rif#constIRI>)
		(object ?iristring))
		=>
(bind ?clipsnode (<http://white.gobo/new-blanknode>))	(assert 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/as-constraint>)
		(object ?clipsnode)))
	(assert 	(TripleTemplate
		(subject ?rifnode)
		(predicate <http://example.com/as-expression>)
		(object ?clipsnode)))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://clips.script/symbol>)
		(object (<http://white.gobo/iri-to-clipsconstant> ?iristring ))))
	(assert 	(TripleTemplate
		(subject ?clipsnode)
		(predicate <http://example.com/as-constraint-needs-additional-conditionals>)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list> ))))

)
;autogenerated group rules

(defrule rule-gen21968 (declare (salience 100))
	(TripleTemplate
		(subject ?base)
		(predicate ?prop)
		(object <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil>))
		=>
	(do-for-all-facts ((?fct TripleTemplate)) (and (eq ?fct:subject ?base) (and (eq ?fct:predicate ?prop)(eq ?fct:object <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil>)))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?base)
		(predicate ?prop)
		(object (<http://www.w3.org/2007/rif-builtin-function#make-list>))))

)

(defrule rule-gen21972 (declare (salience 100))
	(TripleTemplate
		(subject ?base)
		(predicate <http://example.com/triples-to-rdf#as-list>)
		(object ?list))
	(not(exists 	(TripleTemplate
		(subject ?s)
		(predicate ?p)
		(object ?base))))
		=>
	(do-for-all-facts ((?fct TripleTemplate)) (and (eq ?fct:subject ?base) (and (eq ?fct:predicate <http://example.com/triples-to-rdf#as-list>)(eq ?fct:object ?list)))
		(retract ?fct))
)

(defrule rule-gen21979 (declare (salience 100))
	(TripleTemplate
		(subject ?base)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest>)
		(object ?rest))
		(TripleTemplate
		(subject ?base)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#first>)
		(object ?first))
	(test (<http://www.w3.org/2007/rif-builtin-predicate#is-list> ?rest ))
		=>
	(do-for-all-facts ((?fct TripleTemplate)) (and (eq ?fct:subject ?base) (and (eq ?fct:predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest>)(eq ?fct:object ?rest)))
		(retract ?fct))	(do-for-all-facts ((?fct TripleTemplate)) (and (eq ?fct:subject ?base) (and (eq ?fct:predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#first>)(eq ?fct:object ?first)))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?base)
		(predicate <http://example.com/triples-to-rdf#as-list>)
		(object (<http://www.w3.org/2007/rif-builtin-function#insert-before> ?rest "0^^http://www.w3.org/2001/XMLSchema#integer" ?first ))))

)

(defrule rule-gen21986 (declare (salience 100))
	(TripleTemplate
		(subject ?subject)
		(predicate ?prop)
		(object ?listbase))
		(TripleTemplate
		(subject ?listbase)
		(predicate <http://example.com/triples-to-rdf#as-list>)
		(object ?aslist))
		=>
	(do-for-all-facts ((?fct TripleTemplate)) (and (eq ?fct:subject ?subject) (and (eq ?fct:predicate ?prop)(eq ?fct:object ?listbase)))
		(retract ?fct))	(assert 	(TripleTemplate
		(subject ?subject)
		(predicate ?prop)
		(object ?aslist)))

)
