#pragma once

#define _RDF_string_ "http://www.w3.org/2001/XMLSchema#string"
#define _RDF_langString_ "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString"
#define _RDF_PlainLiteral_ "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral"

#define _PRED_ "http://www.w3.org/2007/rif-builtin-predicate#"
#define _FUNC_ "http://www.w3.org/2007/rif-builtin-function#"

//here defined urls
#define _CRIFI_equal_ "http://white.gobo/equal"
#define _CRIFI_success_ "http://white.gobo/success"
#define _CRIFI_percent_encode_ "http://white.gobo/percent-encode"
#define _CRIFI_import_ "http://white.gobo/import"

#define _XS_anyURI_ "http://www.w3.org/2001/XMLSchema#anyURI"
#define _XS_base64Binary_ "http://www.w3.org/2001/XMLSchema#base64Binary"
#define _XS_boolean_ "http://www.w3.org/2001/XMLSchema#boolean"
#define _XS_date_ "http://www.w3.org/2001/XMLSchema#date"
#define _XS_dateTime_ "http://www.w3.org/2001/XMLSchema#dateTime"
#define _XS_dateTimeStamp_ "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
#define _XS_double_ "http://www.w3.org/2001/XMLSchema#double"
#define _XS_float_ "http://www.w3.org/2001/XMLSchema#float"
#define _XS_hexBinary_ "http://www.w3.org/2001/XMLSchema#hexBinary"
#define _XS_decimal_ "http://www.w3.org/2001/XMLSchema#decimal"
#define _XS_integer_ "http://www.w3.org/2001/XMLSchema#integer"
#define _XS_long_ "http://www.w3.org/2001/XMLSchema#long"
#define _XS_int_ "http://www.w3.org/2001/XMLSchema#int"
#define _XS_short_ "http://www.w3.org/2001/XMLSchema#short"
#define _XS_byte_ "http://www.w3.org/2001/XMLSchema#byte"
#define _XS_nonNegativeInteger_ "http://www.w3.org/2001/XMLSchema#nonNegativeInteger"
#define _XS_positiveInteger_ "http://www.w3.org/2001/XMLSchema#positiveInteger"
#define _XS_unsignedLong_ "http://www.w3.org/2001/XMLSchema#unsignedLong"
#define _XS_unsignedInt_ "http://www.w3.org/2001/XMLSchema#unsignedInt"
#define _XS_unsignedShort_ "http://www.w3.org/2001/XMLSchema#unsignedShort"
#define _XS_unsignedByte_ "http://www.w3.org/2001/XMLSchema#unsignedByte"
#define _XS_nonPositiveInteger_ "http://www.w3.org/2001/XMLSchema#nonPositiveInteger"
#define _XS_negativeInteger_ "http://www.w3.org/2001/XMLSchema#negativeInteger"
#define _XS_string_ "http://www.w3.org/2001/XMLSchema#string"
#define _XS_token_ "http://www.w3.org/2001/XMLSchema#token"
#define _XS_language_ "http://www.w3.org/2001/XMLSchema#language"
#define _XS_lang_ "http://www.w3.org/2001/XMLSchema#lang"
#define _XS_Name_ "http://www.w3.org/2001/XMLSchema#Name"
#define _XS_NCName_ "http://www.w3.org/2001/XMLSchema#NCName"
#define _XS_NMTOKEN_ "http://www.w3.org/2001/XMLSchema#NMTOKEN"
#define _XS_time_ "http://www.w3.org/2001/XMLSchema#time"
#define _XS_dayTimeDuration_ "http://www.w3.org/2001/XMLSchema#dayTimeDuration"
#define _XS_yearMonthDuration_ "http://www.w3.org/2001/XMLSchema#yearMonthDuration"
#define _XS_normalizedString_ "http://www.w3.org/2001/XMLSchema#normalizedString"

#define _RDF_PlainLiteral_ "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral"

#define _PRED_literal_not_identical_ "http://www.w3.org/2007/rif-builtin-predicate#literal-not-identical"

#define _FUNC_numeric_add_ "http://www.w3.org/2007/rif-builtin-function#numeric-add"
#define _FUNC_numeric_subtract_ "http://www.w3.org/2007/rif-builtin-function#numeric-subtract"
#define _FUNC_numeric_multiply_ "http://www.w3.org/2007/rif-builtin-function#numeric-multiply"
#define _FUNC_numeric_divide_ "http://www.w3.org/2007/rif-builtin-function#numeric-divide"
#define _FUNC_numeric_integer_divide_ "http://www.w3.org/2007/rif-builtin-function#numeric-integer-divide"
#define _FUNC_numeric_integer_mod_ "http://www.w3.org/2007/rif-builtin-function#numeric-integer-mod"

#define _PRED_numeric_equal_ "http://www.w3.org/2007/rif-builtin-predicate#numeric-equal"
#define _PRED_numeric_not_equal_ "http://www.w3.org/2007/rif-builtin-predicate#numeric-not-equal"
#define _PRED_numeric_less_than_ "http://www.w3.org/2007/rif-builtin-predicate#numeric-less-than"
#define _PRED_numeric_less_than_or_equal_ "http://www.w3.org/2007/rif-builtin-predicate#numeric-less-than-or-equal"
#define _PRED_numeric_greater_than_ "http://www.w3.org/2007/rif-builtin-predicate#numeric-greater-than"
#define _PRED_numeric_greater_than_or_equal_ "http://www.w3.org/2007/rif-builtin-predicate#numeric-greater-than-or-equal"

#define _PRED_is_literal_double_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-double"
#define _PRED_is_literal_float_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-float"
#define _PRED_is_literal_hexBinary_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-hexBinary"
#define _PRED_is_literal_base64Binary_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-base64Binary"
#define _PRED_is_literal_decimal_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-decimal"
#define _PRED_is_literal_integer_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-integer"
#define _PRED_is_literal_long_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-long"
#define _PRED_is_literal_int_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-int"
#define _PRED_is_literal_short_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-short"
#define _PRED_is_literal_byte_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-byte"
#define _PRED_is_literal_nonNegativeInteger_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-nonNegativeInteger"
#define _PRED_is_literal_positiveInteger_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-positiveInteger"
#define _PRED_is_literal_unsignedLong_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-unsignedLong"
#define _PRED_is_literal_unsignedInt_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-unsignedInt"
#define _PRED_is_literal_unsignedShort_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-unsignedShort"
#define _PRED_is_literal_unsignedByte_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-unsignedByte"
#define _PRED_is_literal_nonPositiveInteger_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-nonPositiveInteger"
#define _PRED_is_literal_negativeInteger_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-negativeInteger"

#define _PRED_is_literal_not_double_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-double"
#define _PRED_is_literal_not_float_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-float"
#define _PRED_is_literal_not_hexBinary_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-hexBinary"
#define _PRED_is_literal_not_base64Binary_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-base64Binary"
#define _PRED_is_literal_not_decimal_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-decimal"
#define _PRED_is_literal_not_integer_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-integer"
#define _PRED_is_literal_not_long_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-long"
#define _PRED_is_literal_not_unsignedInt_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-unsignedInt"
#define _PRED_is_literal_not_int_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-int"
#define _PRED_is_literal_not_short_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-short"
#define _PRED_is_literal_not_byte_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-byte"
#define _PRED_is_literal_not_nonNegativeInteger_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-nonNegativeInteger"
#define _PRED_is_literal_not_positiveInteger_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-positiveInteger"
#define _PRED_is_literal_not_unsignedLong_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-unsignedLong"
#define _PRED_is_literal_not_unsignedShort_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-unsignedShort"
#define _PRED_is_literal_not_unsignedByte_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-unsignedByte"
#define _PRED_is_literal_not_nonPositiveInteger_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-nonPositiveInteger"
#define _PRED_is_literal_not_negativeInteger_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-negativeInteger"

#define _PRED_is_literal_PlainLiteral_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-PlainLiteral"
#define _PRED_is_literal_not_PlainLiteral_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-PlainLiteral"


#define _PRED_is_literal_string_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-string"
#define _PRED_is_literal_not_string_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-string"
#define _PRED_is_literal_normalizedString_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-normalizedString"
#define _PRED_is_literal_not_normalizedString_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-normalizedString"
#define _PRED_is_literal_token_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-token"
#define _PRED_is_literal_not_token_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-token"
#define _PRED_is_literal_language_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-language"
#define _PRED_is_literal_not_language_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-language"
#define _PRED_is_literal_Name_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-Name"
#define _PRED_is_literal_not_Name_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-Name"
#define _PRED_is_literal_NCName_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-NCName"
#define _PRED_is_literal_not_NCName_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-NCName"
#define _PRED_is_literal_NMTOKEN_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-NMTOKEN"
#define _PRED_is_literal_not_NMTOKEN_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-NMTOKEN"


#define _PRED_is_list_ "http://www.w3.org/2007/rif-builtin-predicate#is-list"
#define _PRED_list_contains_ "http://www.w3.org/2007/rif-builtin-predicate#list-contains"
#define _FUNC_make_list_ "http://www.w3.org/2007/rif-builtin-function#make-list"
#define _FUNC_count_ "http://www.w3.org/2007/rif-builtin-function#count"
#define _FUNC_get_ "http://www.w3.org/2007/rif-builtin-function#get"
#define _FUNC_sublist_ "http://www.w3.org/2007/rif-builtin-function#sublist"
#define _FUNC_append_ "http://www.w3.org/2007/rif-builtin-function#append"
#define _FUNC_concatenate_ "http://www.w3.org/2007/rif-builtin-function#concatenate"
#define _FUNC_insert_before_ "http://www.w3.org/2007/rif-builtin-function#insert-before"
#define _FUNC_remove_ "http://www.w3.org/2007/rif-builtin-function#remove"
#define _FUNC_reverse_ "http://www.w3.org/2007/rif-builtin-function#reverse"
#define _FUNC_index_of_ "http://www.w3.org/2007/rif-builtin-function#index-of"
#define _FUNC_union_ "http://www.w3.org/2007/rif-builtin-function#union"
#define _FUNC_distinct_values_ "http://www.w3.org/2007/rif-builtin-function#distinct-values"
#define _FUNC_intersect_ "http://www.w3.org/2007/rif-builtin-function#intersect"
#define _FUNC_except_ "http://www.w3.org/2007/rif-builtin-function#except"

#define _FUNC_PlainLiteral_from_string_lang_ "http://www.w3.org/2007/rif-builtin-function#PlainLiteral-from-string-lang"
#define _FUNC_string_from_PlainLiteral_ "http://www.w3.org/2007/rif-builtin-function#string-from-PlainLiteral"
#define _FUNC_lang_from_PlainLiteral_ "http://www.w3.org/2007/rif-builtin-function#lang-from-PlainLiteral"
#define _FUNC_PlainLiteral_compare_ "http://www.w3.org/2007/rif-builtin-function#PlainLiteral-compare"
#define _PRED_matches_language_range_ "http://www.w3.org/2007/rif-builtin-predicate#matches-language-range"


#define _PRED_iri_string_ "http://www.w3.org/2007/rif-builtin-predicate#iri-string"
#define _FUNC_compare_ "http://www.w3.org/2007/rif-builtin-function#compare"
#define _FUNC_concat_ "http://www.w3.org/2007/rif-builtin-function#concat"
#define _FUNC_string_join_ "http://www.w3.org/2007/rif-builtin-function#string-join"
#define _FUNC_substring_ "http://www.w3.org/2007/rif-builtin-function#substring"
#define _FUNC_string_length_ "http://www.w3.org/2007/rif-builtin-function#string-length"
#define _FUNC_upper_case_ "http://www.w3.org/2007/rif-builtin-function#upper-case"
#define _FUNC_lower_case_ "http://www.w3.org/2007/rif-builtin-function#lower-case"
#define _FUNC_encode_for_uri_ "http://www.w3.org/2007/rif-builtin-function#encode-for-uri"
#define _FUNC_iri_to_uri_ "http://www.w3.org/2007/rif-builtin-function#iri-to-uri"
#define _FUNC_escape_html_uri_ "http://www.w3.org/2007/rif-builtin-function#escape-html-uri"
#define _FUNC_substring_before_ "http://www.w3.org/2007/rif-builtin-function#substring-before"
#define _FUNC_substring_after_ "http://www.w3.org/2007/rif-builtin-function#substring-after"
#define _FUNC_replace_ "http://www.w3.org/2007/rif-builtin-function#replace"
#define _PRED_contains_ _PRED_ "contains"
#define _PRED_starts_with_ _PRED_ "starts-with"
#define _PRED_ends_with_ _PRED_ "ends-with"
#define _PRED_matches_ _PRED_ "matches"

#define _PRED_is_literal_date_ _PRED_ "is-literal-date"
#define _PRED_is_literal_dateTime_ _PRED_ "is-literal-dateTime"
#define _PRED_is_literal_dateTimeStamp_ _PRED_ "is-literal-dateTimeStamp"
#define _PRED_is_literal_time_ _PRED_ "is-literal-time"
#define _PRED_is_literal_dayTimeDuration_ _PRED_ "is-literal-dayTimeDuration"
#define _PRED_is_literal_yearMonthDuration_ _PRED_ "is-literal-yearMonthDuration"
#define _PRED_is_literal_not_date_ _PRED_ "is-literal-not-date"
#define _PRED_is_literal_not_dateTime_ _PRED_ "is-literal-not-dateTime"
#define _PRED_is_literal_not_dateTimeStamp_ _PRED_ "is-literal-not-dateTimeStamp"
#define _PRED_is_literal_not_time_ _PRED_ "is-literal-not-time"
#define _PRED_is_literal_not_dayTimeDuration_ _PRED_ "is-literal-not-dayTimeDuration"
#define _PRED_is_literal_not_yearMonthDuration_ _PRED_ "is-literal-not-yearMonthDuration"
#define _FUNC_year_from_dateTime_ _FUNC_ "year-from-dateTime"
#define _FUNC_month_from_dateTime_ _FUNC_ "month-from-dateTime"
#define _FUNC_day_from_dateTime_ _FUNC_ "day-from-dateTime"
#define _FUNC_hours_from_dateTime_ _FUNC_ "hours-from-dateTime"
#define _FUNC_minutes_from_dateTime_ _FUNC_ "minutes-from-dateTime"
#define _FUNC_seconds_from_dateTime_ _FUNC_ "seconds-from-dateTime"
#define _FUNC_year_from_date_ _FUNC_ "year-from-date"
#define _FUNC_month_from_date_ _FUNC_ "month-from-date"
#define _FUNC_day_from_date_ _FUNC_ "day-from-date"
#define _FUNC_hours_from_time_ _FUNC_ "hours-from-time"
#define _FUNC_minutes_from_time_ _FUNC_ "minutes-from-time"
#define _FUNC_seconds_from_time_ _FUNC_ "seconds-from-time"
#define _FUNC_timezone_from_dateTime_ _FUNC_ "timezone-from-dateTime"
#define _FUNC_timezone_from_date_ _FUNC_ "timezone-from-date"
#define _FUNC_timezone_from_time_ _FUNC_ "timezone-from-time"
#define _FUNC_years_from_duration_ _FUNC_ "years-from-duration"
#define _FUNC_months_from_duration_ _FUNC_ "months-from-duration"
#define _FUNC_days_from_duration_ _FUNC_ "days-from-duration"
#define _FUNC_hours_from_duration_ _FUNC_ "hours-from-duration"
#define _FUNC_minutes_from_duration_ _FUNC_ "minutes-from-duration"
#define _FUNC_seconds_from_duration_ _FUNC_ "seconds-from-duration"
#define _FUNC_subtract_dateTimes_ _FUNC_ "subtract-dateTimes"
#define _FUNC_subtract_dates_ _FUNC_ "subtract-dates"
#define _FUNC_subtract_times_ _FUNC_ "subtract-times"
#define _FUNC_add_yearMonthDurations_ _FUNC_ "add-yearMonthDurations"
#define _FUNC_subtract_yearMonthDurations_ _FUNC_ "subtract-yearMonthDurations"
#define _FUNC_multiply_yearMonthDuration_ _FUNC_ "multiply-yearMonthDuration"
#define _FUNC_divide_yearMonthDuration_ _FUNC_ "divide-yearMonthDuration"
#define _FUNC_divide_yearMonthDuration_by_yearMonthDuration_ _FUNC_ "divide-yearMonthDuration-by-yearMonthDuration"
#define _FUNC_add_dayTimeDurations_ _FUNC_ "add-dayTimeDurations"
#define _FUNC_subtract_dayTimeDurations_ _FUNC_ "subtract-dayTimeDurations"
#define _FUNC_multiply_dayTimeDuration_ _FUNC_ "multiply-dayTimeDuration"
#define _FUNC_divide_dayTimeDuration_ _FUNC_ "divide-dayTimeDuration"
#define _FUNC_divide_dayTimeDuration_by_dayTimeDuration_ _FUNC_ "divide-dayTimeDuration-by-dayTimeDuration"
#define _FUNC_add_yearMonthDuration_to_dateTime_ _FUNC_ "add-yearMonthDuration-to-dateTime"
#define _FUNC_add_yearMonthDuration_to_date_ _FUNC_ "add-yearMonthDuration-to-date"
#define _FUNC_add_dayTimeDuration_to_dateTime_ _FUNC_ "add-dayTimeDuration-to-dateTime"
#define _FUNC_add_dayTimeDuration_to_date_ _FUNC_ "add-dayTimeDuration-to-date"
#define _FUNC_add_dayTimeDuration_to_time_ _FUNC_ "add-dayTimeDuration-to-time"
#define _FUNC_subtract_yearMonthDuration_from_date_ _FUNC_ "subtract-yearMonthDuration-from-date"
#define _FUNC_subtract_yearMonthDuration_from_dateTime_ _FUNC_ "subtract-yearMonthDuration-from-dateTime"
#define _FUNC_subtract_dayTimeDuration_from_dateTime_ _FUNC_ "subtract-dayTimeDuration-from-dateTime"
#define _FUNC_subtract_dayTimeDuration_from_date_ _FUNC_ "subtract-dayTimeDuration-from-date"
#define _FUNC_subtract_dayTimeDuration_from_time_ _FUNC_ "subtract-dayTimeDuration-from-time"
#define _PRED_dateTime_equal_ _PRED_ "dateTime-equal"
#define _PRED_dateTime_less_than_ _PRED_ "dateTime-less-than"
#define _PRED_dateTime_greater_than_ _PRED_ "dateTime-greater-than"
#define _PRED_date_equal_ _PRED_ "date-equal"
#define _PRED_date_less_than_ _PRED_ "date-less-than"
#define _PRED_date_greater_than_ _PRED_ "date-greater-than"
#define _PRED_time_equal_ _PRED_ "time-equal"
#define _PRED_time_less_than_ _PRED_ "time-less-than"
#define _PRED_time_greater_than_ _PRED_ "time-greater-than"
#define _PRED_duration_equal_ _PRED_ "duration-equal"
#define _PRED_yearMonthDuration_less_than_ _PRED_ "yearMonthDuration-less-than"
#define _PRED_yearMonthDuration_greater_than_ _PRED_ "yearMonthDuration-greater-than"
#define _PRED_dayTimeDuration_less_than_ _PRED_ "dayTimeDuration-less-than"
#define _PRED_dayTimeDuration_greater_than_ _PRED_ "dayTimeDuration-greater-than"
#define _PRED_dateTime_not_equal_ _PRED_ "dateTime-not-equal"
#define _PRED_dateTime_less_than_or_equal_ _PRED_ "dateTime-less-than-or-equal"
#define _PRED_dateTime_greater_than_or_equal_ _PRED_ "dateTime-greater-than-or-equal"
#define _PRED_date_not_equal_ _PRED_ "date-not-equal"
#define _PRED_date_less_than_or_equal_ _PRED_ "date-less-than-or-equal"
#define _PRED_date_greater_than_or_equal_ _PRED_ "date-greater-than-or-equal"
#define _PRED_time_not_equal_ _PRED_ "time-not-equal"
#define _PRED_time_less_than_or_equal_ _PRED_ "time-less-than-or-equal"
#define _PRED_time_greater_than_or_equal_ _PRED_ "time-greater-than-or-equal"
#define _PRED_duration_not_equal_ _PRED_ "duration-not-equal"
#define _PRED_yearMonthDuration_less_than_or_equal_ _PRED_ "yearMonthDuration-less-than-or-equal"
#define _PRED_yearMonthDuration_greater_than_or_equal_ _PRED_ "yearMonthDuration-greater-than-or-equal"
#define _PRED_dayTimeDuration_less_than_or_equal_ _PRED_ "dayTimeDuration-less-than-or-equal"
#define _PRED_dayTimeDuration_greater_than_or_equal_ _PRED_ "dayTimeDuration-greater-than-or-equal"


#define _RIF_ "http://www.w3.org/2007/rif#"
#define _XML_ "http://www.w3.org/2001/XMLSchema#"
#define _RIFBUILTIN_ "http://www.w3.org/2007/rif-builtin-function#"


///uri has to be macro constant uri
#define ISURI(cmp, cmp_size, uri) ((cmp_size == (sizeof(uri) - 1)) && (0 == memcmp(cmp, uri, sizeof(uri) - 1)))

