#pragma once

#define _RDF_string_ "http://www.w3.org/2001/XMLSchema#string"
#define _RDF_langString_ "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString"
#define _RDF_PlainLiteral_ "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral"

//here defined urls
#define _CRIFI_equal_ "http://white.gobo/equal"
#define _CRIFI_success_ "http://white.gobo/success"
#define _CRIFI_percent_encode_ "http://white.gobo/percent-encode"
#define _CRIFI_import_ "http://white.gobo/import"

#define _XS_anyURI_ "http://www.w3.org/2001/XMLSchema#anyURI"
#define _XS_base64Binary_ "http://www.w3.org/2001/XMLSchema#base64Binary"
#define _XS_boolean_ "http://www.w3.org/2001/XMLSchema#boolean"
#define _XS_date_ "http://www.w3.org/2001/XMLSchema#date"
#define _XS_dateTime_ "http://www.w3.org/2001/XMLSchema#dateTime"
#define _XS_dateTimeStamp_ "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
#define _XS_double_ "http://www.w3.org/2001/XMLSchema#double"
#define _XS_float_ "http://www.w3.org/2001/XMLSchema#float"
#define _XS_hexBinary_ "http://www.w3.org/2001/XMLSchema#hexBinary"
#define _XS_decimal_ "http://www.w3.org/2001/XMLSchema#decimal"
#define _XS_integer_ "http://www.w3.org/2001/XMLSchema#integer"
#define _XS_long_ "http://www.w3.org/2001/XMLSchema#long"
#define _XS_int_ "http://www.w3.org/2001/XMLSchema#int"
#define _XS_short_ "http://www.w3.org/2001/XMLSchema#short"
#define _XS_byte_ "http://www.w3.org/2001/XMLSchema#byte"
#define _XS_nonNegativeInteger_ "http://www.w3.org/2001/XMLSchema#nonNegativeInteger"
#define _XS_positiveInteger_ "http://www.w3.org/2001/XMLSchema#positiveInteger"
#define _XS_unsignedLong_ "http://www.w3.org/2001/XMLSchema#unsignedLong"
#define _XS_unsignedInt_ "http://www.w3.org/2001/XMLSchema#unsignedInt"
#define _XS_unsignedShort_ "http://www.w3.org/2001/XMLSchema#unsignedShort"
#define _XS_unsignedByte_ "http://www.w3.org/2001/XMLSchema#unsignedByte"
#define _XS_nonPositiveInteger_ "http://www.w3.org/2001/XMLSchema#nonPositiveInteger"
#define _XS_negativeInteger_ "http://www.w3.org/2001/XMLSchema#negativeInteger"
#define _XS_string_ "http://www.w3.org/2001/XMLSchema#string"
#define _XS_token_ "http://www.w3.org/2001/XMLSchema#token"
#define _XS_language_ "http://www.w3.org/2001/XMLSchema#language"
#define _XS_Name_ "http://www.w3.org/2001/XMLSchema#Name"
#define _XS_NCName_ "http://www.w3.org/2001/XMLSchema#NCName"
#define _XS_NMToken_ "http://www.w3.org/2001/XMLSchema#NMToken"
#define _XS_time_ "http://www.w3.org/2001/XMLSchema#time"
#define _XS_dayTimeDuration_ "http://www.w3.org/2001/XMLSchema#dayTimeDuration"
#define _XS_yearMonthDuration_ "http://www.w3.org/2001/XMLSchema#yearMonthDuration"

#define _PRED_literal_not_identical_ "http://www.w3.org/2007/rif-builtin-predicate#literal-not-identical"

#define _FUNC_numeric_add_ "http://www.w3.org/2007/rif-builtin-function#numeric-add"
#define _FUNC_numeric_subtract_ "http://www.w3.org/2007/rif-builtin-function#numeric-subtract"
#define _FUNC_numeric_multiply_ "http://www.w3.org/2007/rif-builtin-function#numeric-multiply"
#define _FUNC_numeric_divide_ "http://www.w3.org/2007/rif-builtin-function#numeric-divide"
#define _FUNC_numeric_integer_divide_ "http://www.w3.org/2007/rif-builtin-function#numeric-integer-divide"
#define _FUNC_numeric_integer_mod_ "http://www.w3.org/2007/rif-builtin-function#numeric-integer-mod"

#define _PRED_numeric_equal_ "http://www.w3.org/2007/rif-builtin-predicate#numeric-equal"
#define _PRED_numeric_not_equal_ "http://www.w3.org/2007/rif-builtin-predicate#numeric-not-equal"
#define _PRED_numeric_less_than_ "http://www.w3.org/2007/rif-builtin-predicate#numeric-less-than"
#define _PRED_numeric_less_than_or_equal_ "http://www.w3.org/2007/rif-builtin-predicate#numeric-less-than-or-equal"
#define _PRED_numeric_greater_than_ "http://www.w3.org/2007/rif-builtin-predicate#numeric-greater-than"
#define _PRED_numeric_greater_than_or_equal_ "http://www.w3.org/2007/rif-builtin-predicate#numeric-greater-than-or-equal"

#define _PRED_is_literal_double_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-double"
#define _PRED_is_literal_float_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-float"
#define _PRED_is_literal_hexBinary_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-hexBinary"
#define _PRED_is_literal_base64Binary_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-base64Binary"
#define _PRED_is_literal_decimal_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-decimal"
#define _PRED_is_literal_integer_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-integer"
#define _PRED_is_literal_long_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-long"
#define _PRED_is_literal_int_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-int"
#define _PRED_is_literal_short_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-short"
#define _PRED_is_literal_byte_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-byte"
#define _PRED_is_literal_nonNegativeInteger_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-nonNegativeInteger"
#define _PRED_is_literal_positiveInteger_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-positiveInteger"
#define _PRED_is_literal_unsignedLong_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-unsignedLong"
#define _PRED_is_literal_unsignedInt_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-unsignedInt"
#define _PRED_is_literal_unsignedShort_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-unsignedShort"
#define _PRED_is_literal_unsignedByte_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-unsignedByte"
#define _PRED_is_literal_nonPositiveInteger_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-nonPositiveInteger"
#define _PRED_is_literal_negativeInteger_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-negativeInteger"

#define _PRED_is_literal_not_double_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-double"
#define _PRED_is_literal_not_float_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-float"
#define _PRED_is_literal_not_hexBinary_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-hexBinary"
#define _PRED_is_literal_not_base64Binary_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-base64Binary"
#define _PRED_is_literal_not_decimal_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-decimal"
#define _PRED_is_literal_not_integer_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-integer"
#define _PRED_is_literal_not_long_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-long"
#define _PRED_is_literal_not_unsignedInt_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-unsignedInt"
#define _PRED_is_literal_not_int_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-int"
#define _PRED_is_literal_not_short_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-short"
#define _PRED_is_literal_not_byte_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-byte"
#define _PRED_is_literal_not_nonNegativeInteger_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-nonNegativeInteger"
#define _PRED_is_literal_not_positiveInteger_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-positiveInteger"
#define _PRED_is_literal_not_unsignedLong_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-unsignedLong"
#define _PRED_is_literal_not_unsignedShort_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-unsignedShort"
#define _PRED_is_literal_not_unsignedByte_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-unsignedByte"
#define _PRED_is_literal_not_nonPositiveInteger_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-nonPositiveInteger"
#define _PRED_is_literal_not_negativeInteger_ "http://www.w3.org/2007/rif-builtin-predicate#is-literal-not-negativeInteger"


#define _PRED_is_list_ "http://www.w3.org/2007/rif-builtin-predicate#is-list"
#define _PRED_list_contains_ "http://www.w3.org/2007/rif-builtin-predicate#list-contains"
#define _FUNC_make_list_ "http://www.w3.org/2007/rif-builtin-function#make-list"
#define _FUNC_count_ "http://www.w3.org/2007/rif-builtin-function#count"
#define _FUNC_get_ "http://www.w3.org/2007/rif-builtin-function#get"
#define _FUNC_sublist_ "http://www.w3.org/2007/rif-builtin-function#sublist"
#define _FUNC_append_ "http://www.w3.org/2007/rif-builtin-function#append"
#define _FUNC_concatenate_ "http://www.w3.org/2007/rif-builtin-function#concatenate"
#define _FUNC_insert_before_ "http://www.w3.org/2007/rif-builtin-function#insert-before"
#define _FUNC_remove_ "http://www.w3.org/2007/rif-builtin-function#remove"
#define _FUNC_reverse_ "http://www.w3.org/2007/rif-builtin-function#reverse"
#define _FUNC_index_of_ "http://www.w3.org/2007/rif-builtin-function#index-of"
#define _FUNC_union_ "http://www.w3.org/2007/rif-builtin-function#union"
#define _FUNC_distinct_values_ "http://www.w3.org/2007/rif-builtin-function#distinct-values"
#define _FUNC_intersect_ "http://www.w3.org/2007/rif-builtin-function#intersect"
#define _FUNC_except_ "http://www.w3.org/2007/rif-builtin-function#except"


#define _RIF_ "http://www.w3.org/2007/rif#"
#define _XML_ "http://www.w3.org/2001/XMLSchema#"
#define _RIFBUILTIN_ "http://www.w3.org/2007/rif-builtin-function#"


///uri has to be macro constant uri
#define ISURI(cmp, cmp_size, uri) ((cmp_size == (sizeof(uri) - 1)) && (0 == memcmp(cmp, uri, sizeof(uri) - 1)))

