#pragma once
#include <n3parser.h>
#include "ffi_constants.h"
#include "math_user_defined_functions.h"
#include "pred_user_defined_functions.h"
#include "list_user_defined_functions.h"
#include "binary_user_defined_functions.h"
#include "own_user_defined_functions.h"
#include "plainliteral_user_defined_functions.h"
#include "string_user_defined_functions.h"
#include "time_user_defined_functions.h"
#include "xmlliteral_user_defined_functions.h"
#include "boolean_user_defined_functions.h"
#include "clipsvalue_check_datatype.h"

#include "external_functions.h"

typedef enum {
	CT_static,
	CT_generate,
} ContextType;

typedef struct UDFDescription_ {
	const char *clipsName;
	const char *returnTypes;
	unsigned short minArgs;
	unsigned short maxArgs;
	const char *argTypes;
	UserDefinedFunction *cfp;
	const char *cName;
	ContextType contextType;
	union {
		void *context;
	};
} UDFDescription;

static ContextTypecheck CRegular = {false};
static ContextTypecheck CInvert = {true};

static UDFDescription builtinFunctionList[] = {
	{"<"_CRIFI_equal_">", "*", 2, 2, "*",
		clipsudf_equal, "clipsudf_equal", CT_static, NULL},
	{"<"_CRIFI_percent_encode_">", "s", 1, 1, "s",
		_clipsudf_percent_encoding, "_clipsudf_percent_encoding",  CT_static, NULL},
	{"<"_CRIFI_new_blanknode_">", "*", 0, 0, "*",
		clipsudf_new_blanknode, "clipsudf_new_blanknode", CT_static, NULL},
	{"<"_CRIFI_iri_to_clipsconstant_">", "*", 1, 1, "*",
		clipsudf_iri_to_clipsconstant, "clipsudf_iri_to_clipsconstant",
		CT_static, NULL},
	{"<"_CRIFI_literal_to_clipsconstant_">", "*", 1, 1, "*",
		clipsudf_literal_to_clipsconstant, "clipsudf_literal_to_clipsconstant",
		CT_static, NULL},
	{"PercentDecoding", "s", 1, 1, "s",
		_clipsudf_percent_encoding,
		"_clipsudf_percent_encoding",
		CT_static, NULL},
	{"<"_RIFBUILTIN_"numeric-add>", "s", 2, 2, "s",
		rif_numeric_add, "rif_numeric_add", CT_static, NULL},
	{"<"_RIFBUILTIN_"numeric-subtract>", "s", 2, 2, "s",
		rif_numeric_subtract, "rif_numeric_subtract", CT_static, NULL},
	{"<"_RIFBUILTIN_"numeric-multiply>", "s", 2, 2, "s",
		rif_numeric_multiply, "rif_numeric_multiply", CT_static, NULL},
	{"<"_RIFBUILTIN_"numeric-divide>", "s", 2, 2, "s",
		rif_numeric_divide, "rif_numeric_divide", CT_static, NULL},
	{"<"_RIFBUILTIN_"numeric-integer-divide>", "s", 2, 2, "s",
		rif_numeric_integer_divide, "rif_numeric_integer_divide", CT_static, NULL},
	{"<"_RIFBUILTIN_"numeric-integer-mod>", "s", 2, 2, "s",
		rif_numeric_integer_mod, "rif_numeric_integer_mod", CT_static, NULL},
	{"<"_PRED_numeric_equal_">", "s", 2, 2, "s",
		rif_numeric_equal, "rif_numeric_equal", CT_static, NULL},
	{"<"_PRED_numeric_not_equal_">", "s", 2, 2, "s",
		rif_numeric_not_equal, "rif_numeric_not_equal", CT_static, NULL},
	{"<"_PRED_numeric_less_than_">", "s", 2, 2, "s",
		rif_numeric_less_than, "rif_numeric_less_than", CT_static, NULL},
	{"<"_PRED_numeric_less_than_or_equal_">", "s", 2, 2, "s",
		rif_numeric_less_than_or_equal, "rif_numeric_less_than_or_equal", CT_static, NULL},
	{"<"_PRED_numeric_greater_than_">", "s", 2, 2, "s",
		rif_numeric_greater_than, "rif_numeric_greater_than", CT_static, NULL},
	{"<"_PRED_numeric_greater_than_or_equal_">", "s", 2, 2, "s",
		rif_numeric_greater_than_or_equal, "rif_numeric_greater_than_or_equal", CT_static, NULL},


	{"<"_PRED_literal_not_identical_">", "*", 0, 2, NULL,
		pred_literal_not_identical, "pred_literal_not_identical", CT_static, NULL},


	{"<"_PRED_is_literal_double_">", "b", 1, 1, "s",
		rif_is_literal_double, "rif_is_literal_double", CT_static, &CRegular},
	{"<"_PRED_is_literal_float_">", "b", 1, 1, "s",
		rif_is_literal_float, "rif_is_literal_float", CT_static, &CRegular},
	{"<"_PRED_is_literal_decimal_">", "b", 1, 1, "s",
		rif_is_literal_decimal, "rif_is_literal_decimal", CT_static, &CRegular},
	{"<"_PRED_is_literal_hexBinary_">", "b", 1, 1, "s",
		rif_is_literal_hexBinary, "rif_is_literal_hexBinary", CT_static, &CRegular},
	{"<"_PRED_is_literal_integer_">", "b", 1, 1, "s",
		rif_is_literal_integer, "rif_is_literal_integer", CT_static, &CRegular},
	{"<"_PRED_is_literal_long_">", "b", 1, 1, "s",
		rif_is_literal_long, "rif_is_literal_long", CT_static, &CRegular},
	{"<"_PRED_is_literal_int_">", "b", 1, 1, "s",
		rif_is_literal_int, "rif_is_literal_int", CT_static, &CRegular},
	{"<"_PRED_is_literal_short_">", "b", 1, 1, "s",
		rif_is_literal_short, "rif_is_literal_short", CT_static, &CRegular},
	{"<"_PRED_is_literal_byte_">", "b", 1, 1, "s",
		rif_is_literal_byte, "rif_is_literal_byte", CT_static, &CRegular},
	{"<"_PRED_is_literal_nonNegativeInteger_">", "b", 1, 1, "s",
		rif_is_literal_nonNegativeInteger, "rif_is_literal_nonNegativeInteger", CT_static, &CRegular},
	{"<"_PRED_is_literal_positiveInteger_">", "b", 1, 1, "s",
		rif_is_literal_positiveInteger, "rif_is_literal_positiveInteger", CT_static, &CRegular},
	{"<"_PRED_is_literal_unsignedLong_">", "b", 1, 1, "s",
		rif_is_literal_unsignedLong, "rif_is_literal_unsignedLong", CT_static, &CRegular},
	{"<"_PRED_is_literal_unsignedInt_">", "b", 1, 1, "s",
		rif_is_literal_unsignedInt, "rif_is_literal_unsignedInt", CT_static, &CRegular},
	{"<"_PRED_is_literal_unsignedShort_">", "b", 1, 1, "s",
		rif_is_literal_unsignedShort, "rif_is_literal_unsignedShort", CT_static, &CRegular},
	{"<"_PRED_is_literal_unsignedByte_">", "b", 1, 1, "s",
		rif_is_literal_unsignedByte, "rif_is_literal_unsignedByte", CT_static, &CRegular},
	{"<"_PRED_is_literal_nonPositiveInteger_">", "b", 1, 1, "s",
		rif_is_literal_nonPositiveInteger, "rif_is_literal_nonPositiveInteger", CT_static, &CRegular},
	{"<"_PRED_is_literal_negativeInteger_">", "b", 1, 1, "s",
		rif_is_literal_negativeInteger, "rif_is_literal_negativeInteger", CT_static, &CRegular},

	{"<"_PRED_is_literal_not_double_">", "b", 1, 1, "s",
		rif_is_literal_double, "rif_is_literal_double", CT_static, &CInvert},
	{"<"_PRED_is_literal_not_float_">", "b", 1, 1, "s",
		rif_is_literal_float, "rif_is_literal_float", CT_static, &CInvert},
	{"<"_PRED_is_literal_not_decimal_">", "b", 1, 1, "s",
		rif_is_literal_decimal, "rif_is_literal_decimal", CT_static, &CInvert},
	{"<"_PRED_is_literal_not_hexBinary_">", "b", 1, 1, "s",
		rif_is_literal_hexBinary, "rif_is_literal_hexBinary", CT_static, &CInvert},
	{"<"_PRED_is_literal_not_integer_">", "b", 1, 1, "s",
		rif_is_literal_integer, "rif_is_literal_integer", CT_static, &CInvert},
	{"<"_PRED_is_literal_not_long_">", "b", 1, 1, "s",
		rif_is_literal_long, "rif_is_literal_long", CT_static, &CInvert},
	{"<"_PRED_is_literal_not_int_">", "b", 1, 1, "s",
		rif_is_literal_int, "rif_is_literal_int", CT_static, &CInvert},
	{"<"_PRED_is_literal_not_short_">", "b", 1, 1, "s",
		rif_is_literal_short, "rif_is_literal_short", CT_static, &CInvert},
	{"<"_PRED_is_literal_not_byte_">", "b", 1, 1, "s",
		rif_is_literal_byte, "rif_is_literal_byte", CT_static, &CInvert},
	{"<"_PRED_is_literal_not_nonNegativeInteger_">", "b", 1, 1, "s",
		rif_is_literal_nonNegativeInteger, "rif_is_literal_nonNegativeInteger", CT_static, &CInvert},
	{"<"_PRED_is_literal_not_positiveInteger_">", "b", 1, 1, "s",
		rif_is_literal_positiveInteger, "rif_is_literal_positiveInteger", CT_static, &CInvert},
	{"<"_PRED_is_literal_not_unsignedLong_">", "b", 1, 1, "s",
		rif_is_literal_unsignedLong, "rif_is_literal_unsignedLong", CT_static, &CInvert},
	{"<"_PRED_is_literal_not_unsignedInt_">", "b", 1, 1, "s",
		rif_is_literal_unsignedInt, "rif_is_literal_unsignedInt", CT_static, &CInvert},
	{"<"_PRED_is_literal_not_unsignedShort_">", "b", 1, 1, "s",
		rif_is_literal_unsignedShort, "rif_is_literal_unsignedShort", CT_static, &CInvert},
	{"<"_PRED_is_literal_not_unsignedByte_">", "b", 1, 1, "s",
		rif_is_literal_unsignedByte, "rif_is_literal_unsignedByte", CT_static, &CInvert},
	{"<"_PRED_is_literal_not_nonPositiveInteger_">", "b", 1, 1, "s",
		rif_is_literal_nonPositiveInteger, "rif_is_literal_nonPositiveInteger", CT_static, &CInvert},
	{"<"_PRED_is_literal_not_negativeInteger_">", "b", 1, 1, "s",
		rif_is_literal_negativeInteger, "rif_is_literal_negativeInteger", CT_static, &CInvert},

	{"<"_XS_double_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_double_},
	{"<"_XS_float_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_float_},
	{"<"_XS_decimal_">", "s", 1, 1, "s", rif_cast_as, "rif_cast_as", CT_static, _XS_decimal_},
	{"<"_XS_hexBinary_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_hexBinary_},
	{"<"_XS_base64Binary_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_base64Binary_},
	{"<"_XS_integer_">", "s", 1, 1, "s", rif_cast_as, "rif_cast_as", CT_static, _XS_integer_},
	{"<"_XS_long_">", "s", 1, 1, "s", rif_cast_as, "rif_cast_as", CT_static, _XS_long_},
	{"<"_XS_int_">", "s", 1, 1, "s", rif_cast_as, "rif_cast_as", CT_static, _XS_int_},
	{"<"_XS_short_">", "s", 1, 1, "s", rif_cast_as, "rif_cast_as", CT_static, _XS_short_},
	{"<"_XS_byte_">", "s", 1, 1, "s", rif_cast_as, "rif_cast_as", CT_static, _XS_byte_},
	{"<"_XS_nonNegativeInteger_">", "s", 1, 1, "s", rif_cast_as, "rif_cast_as", CT_static, _XS_nonNegativeInteger_},
	{"<"_XS_positiveInteger_">", "s", 1, 1, "s", rif_cast_as, "rif_cast_as", CT_static, _XS_positiveInteger_},
	{"<"_XS_unsignedLong_">", "s", 1, 1, "s", rif_cast_as, "rif_cast_as", CT_static, _XS_unsignedLong_},
	{"<"_XS_unsignedInt_">", "s", 1, 1, "s", rif_cast_as, "rif_cast_as", CT_static, _XS_unsignedInt_},
	{"<"_XS_unsignedShort_">", "s", 1, 1, "s", rif_cast_as, "rif_cast_as", CT_static, _XS_unsignedShort_},
	{"<"_XS_unsignedByte_">", "s", 1, 1, "s", rif_cast_as, "rif_cast_as", CT_static, _XS_unsignedByte_},
	{"<"_XS_nonPositiveInteger_">", "s", 1, 1, "s", rif_cast_as, "rif_cast_as", CT_static, _XS_nonPositiveInteger_},
	{"<"_XS_negativeInteger_">", "s", 1, 1, "s", rif_cast_as, "rif_cast_as", CT_static, _XS_negativeInteger_},

	{"<"_PRED_is_list_">", "b", 1, 1, "*",
		pred_is_list, "pred_is_list", CT_static, NULL},
	{"<"_PRED_list_contains_">", "b", 2, 2, "*",
		pred_list_contains, "pred_list_contains", CT_static, NULL},
	{"<"_FUNC_make_list_">", "*", 0, UNBOUNDED, "*",
		func_make_list, "func_make_list", CT_static, NULL},
	{"<"_FUNC_count_">", "*", 1, 1, "*",
		func_count, "func_count", CT_static, NULL},
	{"<"_FUNC_get_">", "*", 0, -1, "*",
		func_get, "func_get", CT_static, NULL},
	{"<"_FUNC_sublist_">", "*", 2, 3, "*",
		func_sublist, "func_sublist", CT_static, NULL},
	{"<"_FUNC_append_">", "*", 2, -1, "*",
		func_append, "func_append", CT_static, NULL},
	{"<"_FUNC_concatenate_">", "*", 2, -1, "*",
		func_concatenate, "func_concatenate", CT_static, NULL},
	{"<"_FUNC_insert_before_">", "*", 3, 3, "*",
		func_insert_before, "func_insert_before", CT_static, NULL},
	{"<"_FUNC_remove_">", "*", 2, 2, "*",
		func_remove, "func_remove", CT_static, NULL},
	{"<"_FUNC_reverse_">", "*", 1, 1, "*",
		func_reverse, "func_reverse", CT_static, NULL},
	{"<"_FUNC_index_of_">", "*", 2, 2, "*",
		func_index_of, "func_index_of", CT_static, NULL},
	{"<"_FUNC_union_">", "*", 2, -1, "*",
		func_union, "func_union", CT_static, NULL},
	{"<"_FUNC_distinct_values_">", "*", 1, 1, "*",
		func_distinct_values, "func_distinct_values", CT_static, NULL},
	{"<"_FUNC_intersect_">", "*", 2, -1, "*",
		func_intersect, "func_intersect", CT_static, NULL},
	{"<"_FUNC_except_">", "*", 2, 2, "*",
		func_except, "func_except", CT_static, NULL},

	{"<"_PRED_is_literal_base64Binary_">", "b", 1, 1, "s",
		rif_is_literal_base64Binary, "rif_is_literal_base64Binary",
		CT_static, &CRegular},
	{"<"_PRED_is_literal_not_base64Binary_">", "b", 1, 1, "s",
		rif_is_literal_base64Binary, "rif_is_literal_base64Binary",
		CT_static, &CInvert},

	{"<"_PRED_is_literal_PlainLiteral_">", "b", 1, 1, "s",
		rif_is_literal_PlainLiteral, "rif_is_literal_PlainLiteral",
		CT_static, &CRegular},
	{"<"_PRED_is_literal_not_PlainLiteral_">", "b", 1, 1, "s",
		rif_is_literal_PlainLiteral, "rif_is_literal_PlainLiteral",
		CT_static, &CInvert},

	{"<"_RDF_PlainLiteral_">", "s", 1, 1, "s",
		rif_cast_as_PlainLiteral, "rif_cast_as_PlainLiteral", CT_static, NULL},
	{"<"_FUNC_PlainLiteral_from_string_lang_">", "s", 1, 2, "s",
		rif_PlainLiteral_from_string_lang, "rif_PlainLiteral_from_string_lang",
		CT_static, NULL},
	{"<"_FUNC_string_from_PlainLiteral_">", "s", 1, 1, "s",
		rif_string_from_PlainLiteral, "rif_string_from_PlainLiteral",
		CT_static, NULL},
	{"<"_FUNC_lang_from_PlainLiteral_">", "s", 1, 1, "s",
		rif_lang_from_PlainLiteral, "rif_lang_from_PlainLiteral",
		CT_static, NULL},
	{"<"_FUNC_PlainLiteral_compare_">", "s", 2, 2, "s",
		rif_PlainLiteral_compare, "rif_PlainLiteral_compare",
		CT_static, NULL},
	{"<"_PRED_matches_language_range_">", "s", 2, 2, "s",
		rif_matches_language_range, "rif_matches_language_range",
		CT_static, NULL},

	{"<"_PRED_is_literal_string_">", "b", 1, 1, "s",
		rif_check_datatype, "rif_check_datatype",
		CT_static, &ContextCheck_XS_string},
	{"<"_PRED_is_literal_not_string_">", "b", 1, 1, "s",
		rif_check_datatype, "rif_check_datatype",
		CT_static, &ContextCheck_not_XS_string},
	{"<"_PRED_is_literal_normalizedString_">", "b", 1, 1, "s",
		rif_check_datatype, "rif_check_datatype",
		CT_static, &ContextCheck_XS_normalizedString},
	{"<"_PRED_is_literal_not_normalizedString_">", "b", 1, 1, "s",
		rif_check_datatype, "rif_check_datatype",
		CT_static, &ContextCheck_not_XS_normalizedString},
	{"<"_PRED_is_literal_token_">", "b", 1, 1, "s",
		rif_check_datatype, "rif_check_datatype",
		CT_static, &ContextCheck_XS_token},
	{"<"_PRED_is_literal_not_token_">", "b", 1, 1, "s",
		rif_check_datatype, "rif_check_datatype",
		CT_static, &ContextCheck_not_XS_token},
	{"<"_PRED_is_literal_language_">", "b", 1, 1, "s",
		rif_check_datatype, "rif_check_datatype",
		CT_static, &ContextCheck_XS_language},
	{"<"_PRED_is_literal_not_language_">", "b", 1, 1, "s",
		rif_check_datatype, "rif_check_datatype",
		CT_static, &ContextCheck_not_XS_language},
	{"<"_PRED_is_literal_Name_">", "b", 1, 1, "s",
		rif_check_datatype, "rif_check_datatype",
		CT_static, &ContextCheck_XS_Name},
	{"<"_PRED_is_literal_not_Name_">", "b", 1, 1, "s",
		rif_check_datatype, "rif_check_datatype",
		CT_static, &ContextCheck_not_XS_Name},
	{"<"_PRED_is_literal_NCName_">", "b", 1, 1, "s",
		rif_check_datatype, "rif_check_datatype",
		CT_static, &ContextCheck_XS_NCName},
	{"<"_PRED_is_literal_not_NCName_">", "b", 1, 1, "s",
		rif_check_datatype, "rif_check_datatype",
		CT_static, &ContextCheck_not_XS_NCName},
	{"<"_PRED_is_literal_NMTOKEN_">", "b", 1, 1, "s",
		rif_check_datatype, "rif_check_datatype",
		CT_static, &ContextCheck_XS_NMTOKEN},
	{"<"_PRED_is_literal_not_NMTOKEN_">", "b", 1, 1, "s",
		rif_check_datatype, "rif_check_datatype",
		CT_static, &ContextCheck_not_XS_NMTOKEN},

	{"<"_XS_string_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_string_},
	{"<"_XS_normalizedString_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_normalizedString_},
	{"<"_XS_token_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_token_},
	{"<"_XS_NCName_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_NCName_},
	{"<"_XS_NMTOKEN_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_NMTOKEN_},
	{"<"_XS_Name_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_Name_},
	{"<"_XS_language_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_language_},


	{"<"_PRED_iri_string_">", "b", 2, 2, ";y;s",
		rif_iri_string, "rif_iri_string",
		CT_static, NULL},
	{"<"_FUNC_compare_">", "s", 2, 3, "s",
		rif_compare, "rif_compare",
		CT_static, NULL},
	{"<"_FUNC_concat_">", "s", 2, UNBOUNDED, "s",
		rif_concat, "rif_concat",
		CT_static, NULL},
	{"<"_FUNC_string_join_">", "s", 2, UNBOUNDED, "s",
		rif_string_join, "rif_string_join",
		CT_static, NULL},
	{"<"_FUNC_substring_">", "s", 2, 3, "sid",
		rif_substring, "rif_substring",
		CT_static, NULL},
	{"<"_FUNC_string_length_">", "s", 1, 1, "s",
		rif_string_length, "rif_string_length",
		CT_static, NULL},
	{"<"_FUNC_upper_case_">", "s", 1, 1, "s",
		rif_upper_case, "rif_upper_case",
		CT_static, NULL},
	{"<"_FUNC_lower_case_">", "s", 1, 1, "s",
		rif_lower_case, "rif_lower_case",
		CT_static, NULL},
	{"<"_FUNC_encode_for_uri_">", "s", 1, 1, "s",
		rif_encode_for_uri, "rif_encode_for_uri",
		CT_static, NULL},
	{"<"_FUNC_iri_to_uri_">", "s", 1, 1, "s",
		rif_iri_to_uri, "rif_iri_to_uri",
		CT_static, NULL},
	{"<"_FUNC_escape_html_uri_">", "s", 1, 1, "s",
		rif_escape_html_uri, "rif_escape_html_uri",
		CT_static, NULL},
	{"<"_FUNC_substring_before_">", "s", 2, 2, "s",
		rif_substring_before, "rif_substring_before",
		CT_static, NULL},
	{"<"_FUNC_substring_after_">", "s", 2, 2, "s",
		rif_substring_after, "rif_substring_after",
		CT_static, NULL},
	{"<"_FUNC_replace_">", "s", 3, 4, "s",
		rif_replace, "rif_replace",
		CT_static, NULL},
	{"<"_PRED_contains_ ">", "s", 2, 2, "s",
		rif_contains, "rif_contains",
		CT_static, NULL},
	{"<"_PRED_starts_with_">", "s", 2, 2, "s",
		rif_starts_with, "rif_starts_with",
		CT_static, NULL},
	{"<"_PRED_ends_with_">", "s", 2, 2, "s",
		rif_ends_with, "rif_ends_with",
		CT_static, NULL},
	{"<"_PRED_matches_">", "s", 2, 2, "s",
		rif_matches, "rif_matches",
		CT_static, NULL},



	{"<"_PRED_is_literal_date_">", "b", 1, 1, "s",
		rif_is_literal_date, "rif_is_literal_date",
		CT_static, &CRegular},
	{"<"_PRED_is_literal_dateTime_">", "b", 1, 1, "s",
		rif_is_literal_dateTime, "rif_is_literal_dateTime",
		CT_static, &CRegular},
	{"<"_PRED_is_literal_dateTimeStamp_">", "b", 1, 1, "s",
		rif_is_literal_dateTimeStamp, "rif_is_literal_dateTimeStamp",
		CT_static, &CRegular},
	{"<"_PRED_is_literal_time_">", "b", 1, 1, "s",
		rif_is_literal_time, "rif_is_literal_time",
		CT_static, &CRegular},
	{"<"_PRED_is_literal_dayTimeDuration_">", "b", 1, 1, "s",
		rif_is_literal_dayTimeDuration, "rif_is_literal_dayTimeDuration",
		CT_static, &CRegular},
	{"<"_PRED_is_literal_yearMonthDuration_">", "b", 1, 1, "s",
		rif_is_literal_yearMonthDuration, "rif_is_literal_yearMonthDuration",
		CT_static, &CRegular},
	{"<"_PRED_is_literal_not_date_">", "b", 1, 1, "s",
		rif_is_literal_date, "rif_is_literal_date",
		CT_static, &CInvert},
	{"<"_PRED_is_literal_not_dateTime_">", "b", 1, 1, "s",
		rif_is_literal_dateTime, "rif_is_literal_dateTime",
		CT_static, &CInvert},
	{"<"_PRED_is_literal_not_dateTimeStamp_">", "b", 1, 1, "s",
		rif_is_literal_dateTimeStamp, "rif_is_literal_dateTimeStamp",
		CT_static, &CInvert},
	{"<"_PRED_is_literal_not_time_">", "b", 1, 1, "s",
		rif_is_literal_time, "rif_is_literal_time",
		CT_static, &CInvert},
	{"<"_PRED_is_literal_not_dayTimeDuration_">", "b", 1, 1, "s",
		rif_is_literal_dayTimeDuration, "rif_is_literal_dayTimeDuration",
		CT_static, &CInvert},
	{"<"_PRED_is_literal_not_yearMonthDuration_">", "b", 1, 1, "s",
		rif_is_literal_yearMonthDuration, "rif_is_literal_yearMonthDuration",
		CT_static, &CInvert},

	{"<"_FUNC_year_from_dateTime_">", "s", 1, 1, "s",
		rif_year_from_dateTime, "rif_year_from_dateTime",
		CT_static, NULL},
	{"<"_FUNC_month_from_dateTime_">", "s", 1, 1, "s",
		rif_month_from_dateTime, "rif_month_from_dateTime",
		CT_static, NULL},
	{"<"_FUNC_day_from_dateTime_">", "s", 1, 1, "s",
		rif_day_from_dateTime, "rif_day_from_dateTime",
		CT_static, NULL},
	{"<"_FUNC_hours_from_dateTime_">", "s", 1, 1, "s",
		rif_hours_from_dateTime, "rif_hours_from_dateTime",
		CT_static, NULL},
	{"<"_FUNC_minutes_from_dateTime_">", "s", 1, 1, "s",
		rif_minutes_from_dateTime, "rif_minutes_from_dateTime",
		CT_static, NULL},
	{"<"_FUNC_seconds_from_dateTime_">", "s", 1, 1, "s",
		rif_seconds_from_dateTime, "rif_seconds_from_dateTime",
		CT_static, NULL},
	{"<"_FUNC_year_from_date_">", "s", 1, 1, "s",
		rif_year_from_date, "rif_year_from_date",
		CT_static, NULL},
	{"<"_FUNC_month_from_date_">", "s", 1, 1, "s",
		rif_month_from_date, "rif_month_from_date",
		CT_static, NULL},
	{"<"_FUNC_day_from_date_">", "s", 1, 1, "s",
		rif_day_from_date, "rif_day_from_date",
		CT_static, NULL},
	{"<"_FUNC_hours_from_time_">", "s", 1, 1, "s",
		rif_hours_from_time, "rif_hours_from_time",
		CT_static, NULL},
	{"<"_FUNC_minutes_from_time_">", "s", 1, 1, "s",
		rif_minutes_from_time, "rif_minutes_from_time",
		CT_static, NULL},
	{"<"_FUNC_seconds_from_time_">", "s", 1, 1, "s",
		rif_seconds_from_time, "rif_seconds_from_time",
		CT_static, NULL},
	{"<"_FUNC_timezone_from_dateTime_">", "s", 1, 1, "s",
		rif_timezone_from_dateTime, "rif_timezone_from_dateTime",
		CT_static, NULL},
	{"<"_FUNC_timezone_from_date_">", "s", 1, 1, "s",
		rif_timezone_from_date, "rif_timezone_from_date",
		CT_static, NULL},
	{"<"_FUNC_timezone_from_time_">", "s", 1, 1, "s",
		rif_timezone_from_time, "rif_timezone_from_time",
		CT_static, NULL},
	{"<"_FUNC_years_from_duration_">", "s", 1, 1, "s",
		rif_years_from_duration, "rif_years_from_duration",
		CT_static, NULL},
	{"<"_FUNC_months_from_duration_">", "s", 1, 1, "s",
		rif_months_from_duration, "rif_months_from_duration",
		CT_static, NULL},
	{"<"_FUNC_days_from_duration_">", "s", 1, 1, "s",
		rif_days_from_duration, "rif_days_from_duration",
		CT_static, NULL},
	{"<"_FUNC_hours_from_duration_">", "s", 1, 1, "s",
		rif_hours_from_duration, "rif_hours_from_duration",
		CT_static, NULL},
	{"<"_FUNC_minutes_from_duration_">", "s", 1, 1, "s",
		rif_minutes_from_duration, "rif_minutes_from_duration",
		CT_static, NULL},
	{"<"_FUNC_seconds_from_duration_">", "s", 1, 1, "s",
		rif_seconds_from_duration, "rif_seconds_from_duration",
		CT_static, NULL},
	{"<"_FUNC_subtract_dateTimes_">", "s", 2, 2, "s",
		rif_subtract_dateTimes, "rif_subtract_dateTimes",
		CT_static, NULL},
	{"<"_FUNC_subtract_dates_">", "s", 2, 2, "s",
		rif_subtract_dates, "rif_subtract_dates",
		CT_static, NULL},
	{"<"_FUNC_subtract_times_">", "s", 2, 2, "s",
		rif_subtract_times, "rif_subtract_times",
		CT_static, NULL},
	{"<"_FUNC_add_yearMonthDurations_">", "s", 2, 2, "s",
		rif_add_yearMonthDurations, "rif_add_yearMonthDurations",
		CT_static, NULL},
	{"<"_FUNC_subtract_yearMonthDurations_">", "s", 2, 2, "s",
		rif_subtract_yearMonthDurations, "rif_subtract_yearMonthDurations",
		CT_static, NULL},
	{"<"_FUNC_multiply_yearMonthDuration_">", "s", 2, 2, "s",
		rif_multiply_yearMonthDuration, "rif_multiply_yearMonthDuration",
		CT_static, NULL},
	{"<"_FUNC_divide_yearMonthDuration_">", "s", 2, 2, "s",
		rif_divide_yearMonthDuration, "rif_divide_yearMonthDuration",
		CT_static, NULL},
	{"<"_FUNC_divide_yearMonthDuration_by_yearMonthDuration_">",
		"s", 2, 2, "s",
		rif_divide_yearMonthDuration_by_yearMonthDuration, "rif_divide_yearMonthDuration_by_yearMonthDuration",
		CT_static, NULL},
	{"<"_FUNC_add_dayTimeDurations_">", "s", 2, 2, "s",
		rif_add_dayTimeDurations, "rif_add_dayTimeDurations",
		CT_static, NULL},
	{"<"_FUNC_subtract_dayTimeDurations_">", "s", 2, 2, "s",
		rif_subtract_dayTimeDurations, "rif_subtract_dayTimeDurations",
		CT_static, NULL},
	{"<"_FUNC_multiply_dayTimeDuration_">", "s", 2, 2, "s",
		rif_multiply_dayTimeDuration, "rif_multiply_dayTimeDuration",
		CT_static, NULL},
	{"<"_FUNC_divide_dayTimeDuration_">", "s", 2, 2, "s",
		rif_divide_dayTimeDuration, "rif_divide_dayTimeDuration",
		CT_static, NULL},
	{"<"_FUNC_divide_dayTimeDuration_by_dayTimeDuration_">", "s", 2, 2, "s",
		rif_divide_dayTimeDuration_by_dayTimeDuration, "rif_divide_dayTimeDuration_by_dayTimeDuration",
		CT_static, NULL},
	{"<"_FUNC_add_yearMonthDuration_to_dateTime_">", "s", 2, 2, "s",
		rif_add_yearMonthDuration_to_dateTime, "rif_add_yearMonthDuration_to_dateTime",
		CT_static, NULL},
	{"<"_FUNC_add_yearMonthDuration_to_date_">", "s", 2, 2, "s",
		rif_add_yearMonthDuration_to_date, "rif_add_yearMonthDuration_to_date",
		CT_static, NULL},
	{"<"_FUNC_add_dayTimeDuration_to_dateTime_">", "s", 2, 2, "s",
		rif_add_dayTimeDuration_to_dateTime, "rif_add_dayTimeDuration_to_dateTime",
		CT_static, NULL},
	{"<"_FUNC_add_dayTimeDuration_to_date_">", "s", 2, 2, "s",
		rif_add_dayTimeDuration_to_date, "rif_add_dayTimeDuration_to_date",
		CT_static, NULL},
	{"<"_FUNC_add_dayTimeDuration_to_time_">", "s", 2, 2, "s",
		rif_add_dayTimeDuration_to_time, "rif_add_dayTimeDuration_to_time",
		CT_static, NULL},
	{"<"_FUNC_subtract_yearMonthDuration_from_date_">", "s", 2, 2, "s",
		rif_subtract_yearMonthDuration_from_date, "rif_subtract_yearMonthDuration_from_date",
		CT_static, NULL},
	{"<"_FUNC_subtract_yearMonthDuration_from_dateTime_">", "s", 2, 2, "s",
		rif_subtract_yearMonthDuration_from_dateTime, "rif_subtract_yearMonthDuration_from_dateTime",
		CT_static, NULL},
	{"<"_FUNC_subtract_dayTimeDuration_from_dateTime_">", "s", 2, 2, "s",
		rif_subtract_dayTimeDuration_from_dateTime, "rif_subtract_dayTimeDuration_from_dateTime",
		CT_static, NULL},
	{"<"_FUNC_subtract_dayTimeDuration_from_date_">", "s", 2, 2, "s",
		rif_subtract_dayTimeDuration_from_date, "rif_subtract_dayTimeDuration_from_date",
		CT_static, NULL},
	{"<"_FUNC_subtract_dayTimeDuration_from_time_">", "s", 2, 2, "s",
		rif_subtract_dayTimeDuration_from_time, "rif_subtract_dayTimeDuration_from_time",
		CT_static, NULL},
	{"<"_PRED_dateTime_equal_">", "b", 2, 2, "s",
		rif_dateTime_equal, "rif_dateTime_equal",
		CT_static, &CRegular},
	{"<"_PRED_dateTime_less_than_">", "b", 2, 2, "s",
		rif_dateTime_less_than, "rif_dateTime_less_than",
		CT_static, &CRegular},
	{"<"_PRED_dateTime_greater_than_">", "b", 2, 2, "s",
		rif_dateTime_greater_than, "rif_dateTime_greater_than",
		CT_static, &CRegular},
	{"<"_PRED_date_equal_">", "b", 2, 2, "s",
		rif_date_equal, "rif_date_equal",
		CT_static, &CRegular},
	{"<"_PRED_date_less_than_">", "b", 2, 2, "s",
		rif_date_less_than, "rif_date_less_than",
		CT_static, &CRegular},
	{"<"_PRED_date_greater_than_">", "b", 2, 2, "s",
		rif_date_greater_than, "rif_date_greater_than",
		CT_static, &CRegular},
	{"<"_PRED_time_equal_">", "b", 2, 2, "s",
		rif_time_equal, "rif_time_equal",
		CT_static, &CRegular},
	{"<"_PRED_time_less_than_">", "b", 2, 2, "s",
		rif_time_less_than, "rif_time_less_than",
		CT_static, &CRegular},
	{"<"_PRED_time_greater_than_">", "b", 2, 2, "s",
		rif_time_greater_than, "rif_time_greater_than",
		CT_static, &CRegular},
	{"<"_PRED_duration_equal_">", "b", 2, 2, "s",
		rif_duration_equal, "rif_duration_equal",
		CT_static, &CRegular},
	{"<"_PRED_yearMonthDuration_less_than_">", "b", 2, 2, "s",
		rif_yearMonthDuration_less_than, "rif_yearMonthDuration_less_than",
		CT_static, &CRegular},
	{"<"_PRED_yearMonthDuration_greater_than_">", "b", 2, 2, "s",
		rif_yearMonthDuration_greater_than, "rif_yearMonthDuration_greater_than",
		CT_static, &CRegular},
	{"<"_PRED_dayTimeDuration_less_than_">", "b", 2, 2, "s",
		rif_dayTimeDuration_less_than, "rif_dayTimeDuration_less_than",
		CT_static, &CRegular},
	{"<"_PRED_dayTimeDuration_greater_than_">", "b", 2, 2, "s",
		rif_dayTimeDuration_greater_than, "rif_dayTimeDuration_greater_than",
		CT_static, &CRegular},
	{"<"_PRED_dateTime_not_equal_">", "b", 2, 2, "s",
		rif_dateTime_equal, "rif_dateTime_equal",
		CT_static, &CInvert},
	{"<"_PRED_dateTime_less_than_or_equal_">", "b", 2, 2, "s",
		rif_dateTime_greater_than, "rif_dateTime_greater_than",
		CT_static, &CInvert},
	{"<"_PRED_dateTime_greater_than_or_equal_">", "b", 2, 2, "s",
		rif_dateTime_less_than, "rif_dateTime_less_than",
		CT_static, &CInvert},
	{"<"_PRED_date_not_equal_">", "b", 2, 2, "s",
		rif_date_equal, "rif_date_equal",
		CT_static, &CInvert},
	{"<"_PRED_date_less_than_or_equal_">", "b", 2, 2, "s",
		rif_date_greater_than, "rif_date_greater_than",
		CT_static, &CInvert},
	{"<"_PRED_date_greater_than_or_equal_">", "b", 2, 2, "s",
		rif_date_less_than, "rif_date_less_than",
		CT_static, &CInvert},
	{"<"_PRED_time_not_equal_">", "b", 2, 2, "s",
		rif_time_equal, "rif_time_equal",
		CT_static, &CInvert},
	{"<"_PRED_time_less_than_or_equal_">", "b", 2, 2, "s",
		rif_time_greater_than, "rif_time_greater_than",
		CT_static, &CInvert},
	{"<"_PRED_time_greater_than_or_equal_">", "b", 2, 2, "s",
		rif_time_less_than, "rif_time_less_than",
		CT_static, &CInvert},
	{"<"_PRED_duration_not_equal_">", "b", 2, 2, "s",
		rif_duration_equal, "rif_duration_equal",
		CT_static, &CInvert},
	{"<"_PRED_yearMonthDuration_less_than_or_equal_">", "b", 2, 2, "s",
		rif_yearMonthDuration_greater_than, "rif_yearMonthDuration_greater_than",
		CT_static, &CInvert},
	{"<"_PRED_yearMonthDuration_greater_than_or_equal_">", "b", 2, 2, "s",
		rif_yearMonthDuration_less_than, "rif_yearMonthDuration_less_than",
		CT_static, &CInvert},
	{"<"_PRED_dayTimeDuration_less_than_or_equal_">", "b", 2, 2, "s",
		rif_dayTimeDuration_greater_than, "rif_dayTimeDuration_greater_than",
		CT_static, &CInvert},
	{"<"_PRED_dayTimeDuration_greater_than_or_equal_">", "b", 2, 2, "s",
		rif_dayTimeDuration_less_than, "rif_dayTimeDuration_less_than",
		CT_static, &CInvert},

	{"<"_XS_date_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_date_},
	{"<"_XS_dateTime_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_dateTime_},
	{"<"_XS_dateTimeStamp_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_dateTimeStamp_},
	{"<"_XS_dayTimeDuration_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_dayTimeDuration_},
	{"<"_XS_time_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_time_},
	{"<"_XS_yearMonthDuration_">", "s", 1, 1, "s",
		rif_cast_as, "rif_cast_as", CT_static, _XS_yearMonthDuration_},

	{NULL, NULL, 0,0, NULL, NULL, NULL, CT_static, NULL}
};
