/** \file resource_manager.h
 * Public interface for resource managment
 *
 */
#pragma once
#ifndef _CLIPSRIFRESOURCEMANAGER_H_
#define _CLIPSRIFRESOURCEMANAGER_H_

#include <string>

/**
 * Use in eval: `eval(graph, CHECKFUNCTION)`
 */
#define CHECKFUNCTION "(check-statements)"

/**
 * Helper function to create clips rules logic from OWL.
 *
 * Loads and executes implemented logic.
 *
 * @throw std::runtime_error When some triple in OWLLogicFactlist 
 * 	cant be asserted
 */
std::string *generate_owl_logic(
		struct TriplesLinkedList* OWLLogicFactlist
		);

/**
 * Helper function to create clips rules logic from RIF.
 *
 * Loads and executes implemented logic.
 *
 * @throw std::runtime_error When some triple in RIFLogicFactlist 
 * 	cant be asserted
 */
std::string *generate_rif_logic(
		struct TriplesLinkedList* RIFLogicFactlist
		);

/**
 * Helper function to create clips rules logic from RIF Statement.
 *
 * Loads and executes implemented logic.
 *
 * @throw std::runtime_error When some triple in RIFLogicFactlist 
 * 	cant be asserted
 */
std::string *generate_rif_statement(
		struct TriplesLinkedList* RIFLogicFactlist
		);


/**
 * check if statement as loaded as script generated by generate_rif_statement
 * is true.
 */
bool check_statements(struct clips_graph_container graph);

#endif //_CLIPSRIFRESOURCEMANAGER_H_
