/** \file resource_manager.h
 * Public interface for resource managment
 *
 */
#pragma once
#ifndef _CLIPSRIFRESOURCEMANAGER_H_
#define _CLIPSRIFRESOURCEMANAGER_H_

#include <string>
#include "additional_user_functions.h"

/**
 * Use in eval: `eval(graph, CHECKFUNCTION)`
 */
#define CHECKFUNCTION "(check-statements)"

/**
 * Helper function to create clips rules logic from OWL.
 *
 * Loads and executes implemented logic.
 *
 * @throw std::runtime_error When some triple in OWLLogicFactlist 
 * 	cant be asserted
 */
std::string *generate_owl_logic(
		struct TriplesLinkedList* OWLLogicFactlist
		);

/**
 * Helper function to create clips rules logic from RIF.
 *
 * Loads and executes implemented logic.
 *
 * @throw std::runtime_error When some triple in RIFLogicFactlist 
 * 	cant be asserted
 */
std::string *generate_rif_logic(
		struct TriplesLinkedList* RIFLogicFactlist,
		LoadingFunction loading_function,
		const void *loading_function_context
		);

/**
 * Helper function to create clips rules logic from RIF Statement.
 *
 * Loads and executes implemented logic.
 *
 * @throw std::runtime_error When some triple in RIFLogicFactlist 
 * 	cant be asserted
 */
std::string *generate_rif_statement(
		struct TriplesLinkedList* RIFLogicFactlist
		);

/**
 *
 * Uses _RIF_ENTAILMENT_RDF_
 */
std::string *generate_rdf_entailment(struct TriplesLinkedList* rdf_triples);


/**
 *
 * Uses _RIF_ENTAILMENT_RDFS_
 */
std::string *generate_rdfs_entailment(struct TriplesLinkedList* rdf_triples);


/**
 * _ENTAILMENT_OWLDIRECT_
 */
std::string *generate_owldirect_entailment(struct TriplesLinkedList* owl_triples);


/**
 * check if statement as loaded as script generated by generate_rif_statement
 * is true.
 */
bool check_statements(struct clips_graph_container graph);

#endif //_CLIPSRIFRESOURCEMANAGER_H_
