(defrule rule-gen99 (declare (salience 20))
	(TripleTemplate
		(subject ?X^^http://www.w3.org/2001/XMLSchema#string)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object <http://www.w3.org/2002/07/owl#Ontology>))	=>
(<http://white.gobo/crifi/resource-manager#set_name> ?X^^http://www.w3.org/2001/XMLSchema#string )	(do-for-all-facts ((?fct TripleTemplate)) (and (eq ?fct:subject ?X^^http://www.w3.org/2001/XMLSchema#string) (and (eq ?fct:predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)(eq ?fct:object <http://www.w3.org/2002/07/owl#Ontology>)))
		(retract ?fct))
)
;autogenerated group rules

(defrule rule-gen103 (declare (salience 10))
	(TripleTemplate
		(subject ?X^^http://www.w3.org/2001/XMLSchema#string)
		(predicate <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
		(object ?Y^^http://www.w3.org/2001/XMLSchema#string))	=>
	(assert 	(Atom
		(op <http://white.gobo/crifi/resource-manager/deffacts#member>)
		(args ?X^^http://www.w3.org/2001/XMLSchema#string ?Y^^http://www.w3.org/2001/XMLSchema#string )))

)

(defrule rule-gen107 (declare (salience 10))
	(TripleTemplate
		(subject ?X^^http://www.w3.org/2001/XMLSchema#string)
		(predicate <http://www.w3.org/2000/01/rdf-schema#subclassOf>)
		(object ?Y^^http://www.w3.org/2001/XMLSchema#string))	=>
	(assert 	(Atom
		(op <http://white.gobo/crifi/resource-manager/deffacts#subclass>)
		(args ?X^^http://www.w3.org/2001/XMLSchema#string ?Y^^http://www.w3.org/2001/XMLSchema#string )))

)

(defrule rule-gen111 (declare (salience 10))
	(TripleTemplate
		(subject ?X^^http://www.w3.org/2001/XMLSchema#string)
		(predicate <http://www.w3.org/2002/07/owl#sameAs>)
		(object ?Y^^http://www.w3.org/2001/XMLSchema#string))	=>
	(assert 	(Atom
		(op <http://white.gobo/crifi/resource-manager/deffacts#equal>)
		(args ?X^^http://www.w3.org/2001/XMLSchema#string ?Y^^http://www.w3.org/2001/XMLSchema#string )))

)
;autogenerated group rules

(defrule rule-gen115 (declare (salience -100))
	=>
(<http://white.gobo/crifi/resource-manager#create_script> )
)
