;description

;autogenerated group rules
;autogenerated group rules

(defrule rule-gen37 (declare (salience 10))
	(TripleTemplate
		(subject ?X^^http://www.w3.org/2001/XMLSchema#string)
		(predicate ?Y^^http://www.w3.org/2001/XMLSchema#string)
		(object ?Z^^http://www.w3.org/2001/XMLSchema#string))	=>
	(assert 	(Atom
		(op <http://white.gobo/crifi/resource-manager/deffacts#triple>)
		(args ?X^^http://www.w3.org/2001/XMLSchema#string ?Y^^http://www.w3.org/2001/XMLSchema#string ?Z^^http://www.w3.org/2001/XMLSchema#string )))

)
;autogenerated group rules

(defrule rule-gen41 (declare (salience -100))
	=>
(<http://white.gobo/crifi/resource-manager#create_script> )
)
